Repository LmeSzinc/AzurLaneAutoScript, pull requests merged in 2021-12, with the labels that each got.

#803 Fix: [TW] BOOK_BOX_AUTO & BOOK_CHECK_AUTO assets
  assets/tw/handler/BOOK_BOX_AUTO.png
  assets/tw/handler/BOOK_CHECK_AUTO.png
  module/handler/assets.py
Labels: assets issue

#804 Upd: [TW] SOS module assets
  assets/tw/sos/SIGNAL_LIST_CHECK.png
  assets/tw/template/TEMPLATE_SIGNAL_GOTO.png
  assets/tw/template/TEMPLATE_SIGNAL_SEARCH.png
  module/sos/assets.py
  module/template/assets.py
Labels: assets issue

#838 feat: TryRestart (Debug Settings) will disable error task and try res…
  alas.py
  module/config/argument/args.json
  module/config/i18n/en-US.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
Labels: optimization

#837 Fix: add filter set before retirement
  module/retire/retirement.py
Labels: optimization

#845 Fix: Refresh the shop may using diamonds
  assets/cn/shop/SHOP_BUY_CONFIRM_MISTAKE.png
  assets/en/shop/SHOP_BUY_CONFIRM_MISTAKE.png
  assets/jp/shop/SHOP_BUY_CONFIRM_MISTAKE.png
  assets/tw/shop/SHOP_BUY_CONFIRM_MISTAKE.png
  module/shop/assets.py
  module/shop/shop_reward.py
  module/shop/ui.py
Labels: bug
