Repository LmeSzinc/AzurLaneAutoScript, pull requests merged in 2021-11, with the labels that each got.

#719 添加了CD图配置，可以供以配置不同的fleet
  alas.py
  config/template.json
  module/config/argument/args.json
  module/config/argument/argument.yaml
  module/config/argument/menu.json
  module/config/argument/override.yaml
  module/config/argument/task.yaml
  module/config/config_generated.py
  module/config/config_manual.py
  module/config/config_updater.py
  module/config/i18n/en-US.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
  module/event/campaign_cd.py
Labels: feature

#735 Add: submarine auto search selection
  assets/cn/handler/AUTO_SEARCH_SET_SUB_AUTO.png
  assets/cn/handler/AUTO_SEARCH_SET_SUB_STANDBY.png
  config/template.json
  module/config/argument/args.json
  module/config/argument/argument.yaml
  module/config/config_generated.py
  module/config/i18n/en-US.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
  module/handler/assets.py
  module/handler/auto_search.py
  module/handler/fast_forward.py
Labels: feature

#739 Fix: [JP] use data key notified asset & war archives loading
  assets/jp/handler/USE_DATA_KEY_NOTIFIED.png
  campaign/campaign_war_archives/campaign_base.py
  module/handler/assets.py
Labels: bug, assets issue

#740 ADD: CollectWeeklyMission
  config/template.json
  module/config/argument/args.json
  module/config/argument/argument.yaml
  module/config/config_generated.py
  module/config/i18n/en-US.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
  module/reward/reward.py
Labels: feature

#742 Add: tactical_class adds Exp_Ocr
  assets/cn/tactical/OCR_SKILL_EXP.png
  module/tactical/assets.py
  module/tactical/tactical_class.py
Labels: feature

#750 Fix: [JP]Data_Key&Dock_Filter_Confirm assets
  assets/jp/data_key/DATA_KEY_COLLECT.png
  assets/jp/data_key/DATA_KEY_COLLECTED.png
  assets/jp/retire/DOCK_FILTER_CONFIRM.png
  module/data_key/assets.py
  module/retire/assets.py
Labels: assets issue

#751 fix: Dock_Filter
  module/campaign/gems_farming.py
Labels: optimization

#754 Fix: check expected end before combat status
  module/combat/combat.py
Labels: optimization

#757 Add: WarArchives add Crimson Echoes
  assets/cn/template/TEMPLATE_SIREN_Choukai.gif
  assets/cn/template/TEMPLATE_SIREN_Jintsuu.gif
  assets/cn/template/TEMPLATE_SIREN_Kirishima.gif
  assets/cn/template/TEMPLATE_SIREN_Yuudachi.gif
  assets/cn/war_archives/TEMPLATE_CRIMSON_ECHOES.png
  assets/en/template/TEMPLATE_SIREN_Choukai.gif
  assets/en/template/TEMPLATE_SIREN_Jintsuu.gif
  assets/en/template/TEMPLATE_SIREN_Kirishima.gif
  assets/en/template/TEMPLATE_SIREN_Yuudachi.gif
  assets/jp/template/TEMPLATE_SIREN_Choukai.gif
  assets/jp/template/TEMPLATE_SIREN_Jintsuu.gif
  assets/jp/template/TEMPLATE_SIREN_Kirishima.gif
  assets/jp/template/TEMPLATE_SIREN_Yuudachi.gif
  assets/tw/template/TEMPLATE_SIREN_Choukai.gif
  assets/tw/template/TEMPLATE_SIREN_Jintsuu.gif
  assets/tw/template/TEMPLATE_SIREN_Kirishima.gif
  assets/tw/template/TEMPLATE_SIREN_Yuudachi.gif
  campaign/Readme.md
  campaign/war_archives_20181227_cn/a1.py
  campaign/war_archives_20181227_cn/a2.py
  campaign/war_archives_20181227_cn/a3.py
  campaign/war_archives_20181227_cn/b1.py
  campaign/war_archives_20181227_cn/b2.py
  campaign/war_archives_20181227_cn/b3.py
  campaign/war_archives_20181227_cn/c1.py
  campaign/war_archives_20181227_cn/c2.py
  campaign/war_archives_20181227_cn/c3.py
  campaign/war_archives_20181227_cn/d1.py
  campaign/war_archives_20181227_cn/d2.py
  campaign/war_archives_20181227_cn/d3.py
  config/template.json
  dev_tools/map_extractor.py
  module/config/argument/args.json
  module/config/i18n/en-US.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
  module/template/assets.py
  module/war_archives/assets.py
  module/war_archives/dictionary.py
Labels: feature

#759 Fix[tw]: Asserts replace RESHMENU_GOTO_RESEARCH
  assets/tw/ui/RESHMENU_GOTO_RESEARCH.png
  module/ui/assets.py
Labels: assets issue

#768 Fix: [TW] guild, os assets (#765)
  assets/tw/guild/GUILD_DISPATCH_FLEET_UNFILLED.png
  assets/tw/guild/GUILD_DISPATCH_QUICK.png
  assets/tw/guild/GUILD_DISPATCH_RECOMMEND.png
  assets/tw/guild/GUILD_OPERATIONS_ACTIVE_CHECK.png
  assets/tw/os_ash/BATTLE_STATUS.png
  assets/tw/os_ash/BEACON_REWARD.png
  assets/tw/os_handler/SHOP_BUY_CONFIRM.png
  module/guild/assets.py
  module/os_ash/assets.py
  module/os_handler/assets.py
Labels: assets issue

#772 Fix: Refactor RewardTacticalClass
  config/template.json
  module/config/argument/args.json
  module/config/argument/argument.yaml
  module/config/argument/task.yaml
  module/config/config_generated.py
  module/config/i18n/en-US.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
  module/tactical/tactical_class.py
Labels: optimization, feature

#783 Add: [TW] World-spanning Arclight
  campaign/Readme.md
  module/config/i18n/zh-TW.json
Labels: assets issue

#780 Linux + Docker support
  dev_tools/Docker-run.sh
  dev_tools/Dockerfile
Labels: dependencies, feature
