Repository LmeSzinc/AzurLaneAutoScript, pull requests merged in 2021-09, with the labels that each got.

#607 Fix: [TW] Equipment assets in gems farming
  assets/tw/equipment/EQUIPMENT_SCROLL_BOTTOM.png
  assets/tw/equipment/EQUIPPING_OFF.png
  assets/tw/equipment/EQUIPPING_ON.BUTTON.png
  assets/tw/equipment/EQUIPPING_ON.png
  assets/tw/equipment/EQUIP_CONFIRM.png
  assets/tw/equipment/EQUIP_OFF.png
  assets/tw/equipment/EQUIP_SAVE.png
  assets/tw/equipment/EQUIP_SCROLL.png
  assets/tw/equipment/EQUIP_TAKE_ON_0.png
  assets/tw/equipment/EQUIP_TAKE_ON_1.png
  assets/tw/equipment/EQUIP_TAKE_ON_2.png
  assets/tw/equipment/EQUIP_TAKE_ON_3.png
  assets/tw/equipment/EQUIP_TAKE_ON_4.png
  assets/tw/equipment/SHIP_INFO_EQUIPMENT_CHECK.png
  assets/tw/equipment/UPGRADE_ENTER.png
  assets/tw/equipment/UPGRADE_ENTER_CHECK.png
  assets/tw/equipment/UPGRADE_QUIT.png
  assets/tw/retire/RETIRE_COIN.png
  assets/tw/retire/TEMPLATE_BOGUE.png
  assets/tw/retire/TEMPLATE_HERMES.png
  assets/tw/retire/TEMPLATE_LANGLEY.png
  assets/tw/retire/TEMPLATE_RANGER.png
  module/equipment/assets.py
  module/retire/assets.py
Labels: assets issue

#609 Fix: update war_archives_20190620_map
  campaign/war_archives_20190620_en/sp2.py
  campaign/war_archives_20190620_en/sp3.py
Labels: bug

#611 Fix: handle ash beacon outdate in preparation page
  module/os_ash/ash.py
Labels: bug

#625 [Fix]: gems auto farming
  module/campaign/gems_farming.py
  module/equipment/equipment_change.py
Labels: bug

#627 Add: [TW] Dreamwaker's Butterfly
  campaign/Readme.md
  module/config/event.py
Labels: feature

#631 [fix]: "list.remove(x): x not in list" error
  module/equipment/equipment_change.py
Labels: bug

#632 Add: Daily Gacha Reward
  assets/cn/gacha/BUILD_CUBE_COUNT.png
  assets/cn/gacha/BUILD_FINISH_RESULTS.png
  assets/cn/gacha/BUILD_MINUS.png
  assets/cn/gacha/BUILD_PLUS.png
  assets/cn/gacha/BUILD_SUBMIT_COUNT.png
  assets/cn/gacha/BUILD_SUBMIT_WW_COUNT.png
  assets/cn/gacha/BUILD_SUBMIT_WW_ORDERS.png
  assets/cn/gacha/BUILD_WW_CHECK.png
  assets/en/gacha/BUILD_CUBE_COUNT.png
  assets/en/gacha/BUILD_FINISH_RESULTS.png
  assets/en/gacha/BUILD_MINUS.png
  assets/en/gacha/BUILD_PLUS.png
  assets/en/gacha/BUILD_SUBMIT_COUNT.png
  assets/en/gacha/BUILD_SUBMIT_WW_COUNT.png
  assets/en/gacha/BUILD_SUBMIT_WW_ORDERS.png
  assets/en/gacha/BUILD_WW_CHECK.png
  assets/jp/gacha/BUILD_CUBE_COUNT.png
  assets/jp/gacha/BUILD_FINISH_RESULTS.png
  assets/jp/gacha/BUILD_MINUS.png
  assets/jp/gacha/BUILD_PLUS.png
  assets/jp/gacha/BUILD_SUBMIT_COUNT.png
  assets/jp/gacha/BUILD_SUBMIT_WW_COUNT.png
  assets/jp/gacha/BUILD_SUBMIT_WW_ORDERS.png
  assets/jp/gacha/BUILD_WW_CHECK.png
  assets/tw/gacha/BUILD_CUBE_COUNT.png
  assets/tw/gacha/BUILD_FINISH_RESULTS.png
  assets/tw/gacha/BUILD_MINUS.png
  assets/tw/gacha/BUILD_PLUS.png
  assets/tw/gacha/BUILD_SUBMIT_COUNT.png
  assets/tw/gacha/BUILD_SUBMIT_WW_COUNT.png
  assets/tw/gacha/BUILD_SUBMIT_WW_ORDERS.png
  assets/tw/gacha/BUILD_WW_CHECK.png
  config/template.ini
  module/config/argparser.py
  module/config/argparser_en.py
  module/config/argparser_jp.py
  module/config/argparser_tw.py
  module/config/config.py
  module/config/dictionary.py
  module/gacha/assets.py
  module/gacha/gacha_reward.py
  module/gacha/ui.py
  module/reward/reward.py
Labels: feature
