Repository LmeSzinc/AzurLaneAutoScript, pull requests merged in 2022-01, with the labels that each got.

#854 Fix: [CN]Bilibili: user agreement and login btn
  module/handler/login.py
Labels: bug

#873 Fix: [CN]Bilibili: user agreement extend outside image
  module/handler/login.py
Labels: bug

#886 Fix: executable_path maybe None
  deploy/installer.py
Labels: bug

#894 Opt: Rich logging
  assets/gui/css/alas-mobile.css
  assets/gui/css/alas.css
  assets/gui/css/dark-alas.css
  assets/gui/css/light-alas.css
  module/daemon/benchmark.py
  module/logger.py
  module/webui/app.py
  module/webui/process_manager.py
  module/webui/setting.py
  module/webui/utils.py
  module/webui/widgets.py
  requirements-in.txt
  requirements.txt
Labels: feature

#893 Add: Use tuning samples option in OpsiDaily
  assets/cn/os_handler/TEMPLATE_STORAGE_COMBAT.png
  assets/cn/os_handler/TEMPLATE_STORAGE_OFFENSE.png
  assets/cn/os_handler/TEMPLATE_STORAGE_QUALITY_COMBAT.png
  assets/cn/os_handler/TEMPLATE_STORAGE_QUALITY_OFFENSE.png
  assets/cn/os_handler/TEMPLATE_STORAGE_QUALITY_SURVIVAL.png
  assets/cn/os_handler/TEMPLATE_STORAGE_SURVIVAL.png
  assets/en/os_handler/TEMPLATE_STORAGE_COMBAT.png
  assets/en/os_handler/TEMPLATE_STORAGE_OFFENSE.png
  assets/en/os_handler/TEMPLATE_STORAGE_QUALITY_COMBAT.png
  assets/en/os_handler/TEMPLATE_STORAGE_QUALITY_OFFENSE.png
  assets/en/os_handler/TEMPLATE_STORAGE_QUALITY_SURVIVAL.png
  assets/en/os_handler/TEMPLATE_STORAGE_SURVIVAL.png
  assets/jp/os_handler/TEMPLATE_STORAGE_COMBAT.png
  assets/jp/os_handler/TEMPLATE_STORAGE_OFFENSE.png
  assets/jp/os_handler/TEMPLATE_STORAGE_QUALITY_COMBAT.png
  assets/jp/os_handler/TEMPLATE_STORAGE_QUALITY_OFFENSE.png
  assets/jp/os_handler/TEMPLATE_STORAGE_QUALITY_SURVIVAL.png
  assets/jp/os_handler/TEMPLATE_STORAGE_SURVIVAL.png
  assets/tw/os_handler/TEMPLATE_STORAGE_COMBAT.png
  assets/tw/os_handler/TEMPLATE_STORAGE_OFFENSE.png
  assets/tw/os_handler/TEMPLATE_STORAGE_QUALITY_COMBAT.png
  assets/tw/os_handler/TEMPLATE_STORAGE_QUALITY_OFFENSE.png
  assets/tw/os_handler/TEMPLATE_STORAGE_QUALITY_SURVIVAL.png
  assets/tw/os_handler/TEMPLATE_STORAGE_SURVIVAL.png
  config/template.json
  module/config/argument/args.json
  module/config/argument/argument.yaml
  module/config/config_generated.py
  module/config/i18n/en-US.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
  module/os/operation_siren.py
  module/os_handler/assets.py
  module/os_handler/storage.py
Labels: feature

#898 Fix: handle research remain 00:00:00 correctly
  module/research/research.py
Labels: bug

#891 Opt: shop revamp final
  assets/cn/shop/SHOP_CLICK_SAFE_AREA.png
  assets/en/shop/SHOP_CLICK_SAFE_AREA.png
  assets/jp/shop/SHOP_CLICK_SAFE_AREA.png
  assets/shop/guild/PR.png
  assets/shop/guild/ShipT2.png
  assets/shop/guild/ShipT3.png
  assets/shop/guild_cn/PR.png
  assets/shop/guild_cn/ShipT2.png
  assets/shop/guild_cn/ShipT3.png
  assets/shop/medal/DRAgirS4.png
  assets/shop/medal/DRAzumaS2.png
  assets/shop/medal/DRDrakeS3.png
  assets/shop/medal/DRFriedrichS2.png
  assets/shop/medal/DRHakuryuS4.png
  assets/shop/medal/DRS2.png
  assets/shop/medal/DRS3.png
  assets/shop/medal/DRS4.png
  assets/shop/medal/PRAnchorageS4.png
  assets/shop/medal/PRAugustS4.png
  assets/shop/medal/PRChampagneS3.png
  assets/shop/medal/PRCheshireS3.png
  assets/shop/medal/PRGascogneS2.png
  assets/shop/medal/PRGeorgiaS2.png
  assets/shop/medal/PRIbukiS1.png
  assets/shop/medal/PRIzumoS1.png
  assets/shop/medal/PRKitakazeS2.png
  assets/shop/medal/PRMainzS3.png
  assets/shop/medal/PRMarcoPoloS4.png
  assets/shop/medal/PRMonarchS1.png
  assets/shop/medal/PRNeptuneS1.png
  assets/shop/medal/PROdinS3.png
  assets/shop/medal/PRRoonS1.png
  assets/shop/medal/PRS1.png
  assets/shop/medal/PRS2.png
  assets/shop/medal/PRS3.png
  assets/shop/medal/PRS4.png
  assets/shop/medal/PRSaintLouisS1.png
  assets/shop/medal/PRSeattleS2.png
  assets/tw/shop/SHOP_CLICK_SAFE_AREA.png
  config/template.json
  module/config/argument/args.json
  module/config/argument/argument.yaml
  module/config/config.py
  module/config/config_generated.py
  module/config/config_updater.py
  module/gacha/gacha_reward.py
  module/redirect_utils/shop_filter.py
  module/shipyard/shipyard_reward.py
  module/shop/assets.py
  module/shop/base.py
  module/shop/base_globals.py
  module/shop/shop_core.py
  module/shop/shop_general.py
  module/shop/shop_guild.py
  module/shop/shop_guild_globals.py
  module/shop/shop_medal.py
  module/shop/shop_merit.py
  module/shop/shop_reward.py
  module/shop/ui.py
Labels: optimization

#903 Fix: Correct WarArchives's task delay logic
  module/war_archives/war_archives.py
Labels: bug
