Repository LmeSzinc/AzurLaneAutoScript, pull requests merged in 2022-06, with the labels that each got.

#1180 Opt: Update Emotion Record if Emotion Value is changed
  module/webui/app.py
Labels: optimization

#1163 Opt: Enforce research when get a low-quality project Ver2
  module/research/preset.py
  module/research/project.py
  module/research/research.py
Labels: optimization

#1185 Fix: shop module refactor; medal shop adjustment
  assets/cn/shop/SHOP_MEDAL.png
  assets/en/shop/SHOP_MEDAL.png
  assets/jp/shop/SHOP_MEDAL.png
  assets/shop/cost/Medal.png
  assets/shop/medal/PlateWildT1.png
  assets/shop/medal/PlateWildT2.png
  assets/shop/medal/PlateWildT3.png
  assets/shop/medal/RetrofitT1.png
  assets/shop/medal/RetrofitT2.png
  assets/shop/medal/RetrofitT3.png
  assets/tw/shop/SHOP_MEDAL.png
  config/template.json
  deploy/config.py
  deploy/template
  gui.py
  module/config/argument/args.json
  module/config/argument/argument.yaml
  module/config/config_generated.py
  module/config/i18n/en-US.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
  module/shop/assets.py
  module/shop/base.py
  module/shop/clerk.py
  module/shop/shop_core.py
  module/shop/shop_general.py
  module/shop/shop_guild.py
  module/shop/shop_medal.py
  module/shop/shop_merit.py
  module/shop/shop_reward.py
  module/shop/shop_select_globals.py
  module/shop/ui.py
  module/webui/app.py
Labels: optimization

#1189 Fix: TW server meowfficer buy
  assets/tw/meowfficer/OCR_MEOWFFICER.png
  module/meowfficer/assets.py
Labels: assets issue, Server: TW

#1167 Add: adb restart
  config/template.json
  module/config/argument/args.json
  module/config/argument/argument.yaml
  module/config/config_generated.py
  module/config/i18n/en-US.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
  module/device/connection.py
Labels: optimization, good first issue

#1240 Fix nc server loopback IP for AVD (fix #1236)
  module/device/connection.py
Labels: bug, emulator issue

#1257 Opt: Optimized output when execute 'taskkill'
  deploy/alas.py
  deploy/config.py
  deploy/emulator.py
Labels: optimization

#1266 Fix: Alas webui shutdown caused by datetime error
  module/config/config.py
Labels: optimization

#1271 Fix: [TW] raid_check assets
  assets/tw/ui/RAID_CHECK.png
  module/ui/assets.py
Labels: assets issue, Server: TW
