Repository LmeSzinc/AzurLaneAutoScript, pull requests merged in 2022-08, with the labels that each got.

#1212 Add: Check server status before running a task, wait until available
  alas.py
  config/template.json
  module/config/argument/args.json
  module/config/argument/argument.yaml
  module/config/config_generated.py
  module/config/config_updater.py
  module/config/i18n/en-US.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
  module/config/server.py
  module/server_checker.py
Labels: feature

#1490 Add:Force collect data key
  module/config/argument/args.json
  module/config/argument/argument.yaml
  module/config/config_generated.py
  module/config/i18n/en-US.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
  module/data_key/data_key.py
Labels: good first issue, feature

#1495 Fix: [TW] OPTS_INFO_D
  assets/tw/combat/OPTS_INFO_D.png
  module/combat/assets.py
Labels: assets issue, Server: TW

#1442 Fix: wrong OCR result for build ticket count
  assets/cn/gacha/BUILD_TICKET_CHECK.png
  assets/en/gacha/BUILD_TICKET_CHECK.png
  assets/jp/gacha/BUILD_TICKET_CHECK.png
  assets/tw/gacha/BUILD_TICKET_CHECK.png
  module/gacha/assets.py
  module/gacha/gacha_reward.py
Labels: bug

#1485 Upt: Assets of equipment_change
  assets/cn/equipment/EQUIPMENT_CLOSE.png
  assets/cn/equipment/EQUIPMENT_OPEN.png
  assets/cn/equipment/EQUIP_1.png
  assets/cn/equipment/EQUIP_2.png
  assets/cn/equipment/EQUIP_3.png
  assets/cn/equipment/EQUIP_OFF.png
  assets/en/equipment/EQUIPMENT_CLOSE.png
  assets/en/equipment/EQUIPMENT_OPEN.png
  assets/en/equipment/EQUIP_1.png
  assets/en/equipment/EQUIP_2.png
  assets/en/equipment/EQUIP_3.png
  assets/en/equipment/EQUIP_OFF.png
  assets/jp/equipment/EQUIPMENT_CLOSE.png
  assets/jp/equipment/EQUIPMENT_OPEN.png
  assets/jp/equipment/EQUIP_1.png
  assets/jp/equipment/EQUIP_2.png
  assets/jp/equipment/EQUIP_3.png
  assets/jp/equipment/EQUIP_OFF.png
  assets/tw/equipment/EQUIPMENT_CLOSE.png
  assets/tw/equipment/EQUIPMENT_OPEN.png
  assets/tw/equipment/EQUIP_1.png
  assets/tw/equipment/EQUIP_2.png
  assets/tw/equipment/EQUIP_3.png
  assets/tw/equipment/EQUIP_OFF.png
  module/campaign/gems_farming.py
  module/equipment/assets.py
  module/equipment/equipment.py
  module/equipment/equipment_change.py
Labels: bug, assets issue

#1499 Fix: minor translation fixs in gemsfarming
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
Labels: optimization

#1500 Fix: Delay research incorrectly when project nearly complete
  module/research/research.py
Labels: bug

#1511 Add: Suffix of Comission Supported
  module/commission/commission.py
  module/commission/project.py
Labels: optimization

#1326 Add: Emulator auto detect and restart
  config/template.json
  module/config/argument/args.json
  module/config/argument/argument.yaml
  module/config/argument/task.yaml
  module/config/config_generated.py
  module/config/i18n/en-US.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
  module/device/connection.py
  module/device/device.py
  module/device/emulator.py
  module/device/screenshot.py
  module/exception.py
  module/handler/login.py
Labels: feature

#1524 Fix: Incompele gems_farming stop condition
  module/campaign/gems_farming.py
Labels: bug

#1531 Upd: [JP] study new skill assets
  assets/jp/tactical/ADD_NEW_STUDENT.png
  assets/jp/tactical/TACTICAL_META.png
  assets/jp/tactical/TACTICAL_SKILL_LIST.png
  module/tactical/assets.py
Labels: assets issue, Server: JP

#1530 Upd: Modified some options for restart emulator
  config/template.json
  module/config/argument/args.json
  module/config/argument/argument.yaml
  module/config/config_generated.py
  module/config/i18n/en-US.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
  module/device/emulator.py
  module/handler/login.py
Labels: optimization

#1529 Add: Use tech box & Disassemble equipments
  .gitignore
  assets/cn/storage/BOX_USE.BUTTON.png
  assets/cn/storage/BOX_USE.png
  assets/cn/storage/DISASSEMBLE.BUTTON.png
  assets/cn/storage/DISASSEMBLE.png
  assets/cn/storage/DISASSEMBLE_CANCEL.BUTTON.png
  assets/cn/storage/DISASSEMBLE_CANCEL.png
  assets/cn/storage/DISASSEMBLE_CONFIRM.BUTTON.png
  assets/cn/storage/DISASSEMBLE_CONFIRM.png
  assets/cn/storage/DISASSEMBLE_COUNT_OCR.png
  assets/cn/storage/DISASSEMBLE_POPUP_CONFIRM.BUTTON.png
  assets/cn/storage/DISASSEMBLE_POPUP_CONFIRM.png
  assets/cn/storage/EQUIPMENT_EMPTY.png
  assets/cn/storage/EQUIPMENT_ENTER.BUTTON.png
  assets/cn/storage/EQUIPMENT_ENTER.png
  assets/cn/storage/EQUIPMENT_FILTER.BUTTON.png
  assets/cn/storage/EQUIPMENT_FILTER.png
  assets/cn/storage/EQUIPMENT_FILTER_CONFIRM.BUTTON.png
  assets/cn/storage/EQUIPMENT_FILTER_CONFIRM.png
  assets/cn/storage/EQUIPMENT_FULL.BUTTON.png
  assets/cn/storage/EQUIPMENT_FULL.png
  assets/cn/storage/MATERIAL_CHECK.png
  assets/cn/storage/MATERIAL_ENTER.BUTTON.png
  assets/cn/storage/MATERIAL_ENTER.png
  assets/cn/storage/MATERIAL_STABLE_CHECK.png
  assets/cn/storage/METERIAL_SCROLL.png
  assets/cn/storage/TEMPLATE_BOX_T1.png
  assets/cn/storage/TEMPLATE_BOX_T2.png
  assets/cn/storage/TEMPLATE_BOX_T3.png
  assets/cn/storage/TEMPLATE_BOX_T4.png
  assets/cn/ui/MAIN_GOTO_STORAGE.png
  assets/cn/ui/STORAGE_CHECK.png
  assets/en/storage/TEMPLATE_BOX_T1.png
  assets/en/storage/TEMPLATE_BOX_T2.png
  assets/en/storage/TEMPLATE_BOX_T3.png
  assets/en/storage/TEMPLATE_BOX_T4.png
  assets/jp/storage/TEMPLATE_BOX_T1.png
  assets/jp/storage/TEMPLATE_BOX_T2.png
  assets/jp/storage/TEMPLATE_BOX_T3.png
  assets/jp/storage/TEMPLATE_BOX_T4.png
  assets/tw/storage/TEMPLATE_BOX_T1.png
  assets/tw/storage/TEMPLATE_BOX_T2.png
  assets/tw/storage/TEMPLATE_BOX_T3.png
  assets/tw/storage/TEMPLATE_BOX_T4.png
  module/storage/assets.py
  module/storage/storage.py
  module/storage/ui.py
  module/ui/assets.py
  module/ui/page.py
Labels: feature

#1509 Add: TaskBalancer
  assets/cn/campaign/OCR_COIN.png
  assets/en/campaign/OCR_COIN.png
  assets/jp/campaign/OCR_COIN.png
  assets/tw/campaign/OCR_COIN.png
  config/template.json
  module/campaign/assets.py
  module/campaign/run.py
  module/config/argument/args.json
  module/config/argument/argument.yaml
  module/config/argument/task.yaml
  module/config/config.py
  module/config/config_generated.py
  module/config/i18n/en-US.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
Labels: feature

#1556 Fix: Restart the emulator after startup timeout
  module/device/connection.py
  module/device/emulator.py
Labels: bug

#1562 Fix: Wrong action point value of action point box
  module/os_handler/action_point.py
Labels: bug
