Repository LmeSzinc/AzurLaneAutoScript, pull requests merged in 2022-02, with the labels that each got.

#926 Fix: Add Entrance of Empyreal Tagicomedy WarArchives
  assets/cn/war_archives/TEMPLATE_EMPYREAL_TRAGICOMEDY.png
  campaign/war_archives_20190911_cn/campaign_base.py
  module/war_archives/assets.py
  module/war_archives/dictionary.py
Labels: assets issue

#923 Opt: meowfficer refactor
  assets/cn/meowfficer/MEOWFFICER_CANCEL.png
  assets/cn/meowfficer/MEOWFFICER_ENHANCE_CONFIRM.png
  assets/cn/meowfficer/MEOWFFICER_ENHANCE_ENTER.png
  assets/cn/meowfficer/MEOWFFICER_FEED_CANCEL.png
  assets/cn/meowfficer/MEOWFFICER_FEED_CONFIRM.png
  assets/cn/meowfficer/MEOWFFICER_FEED_ENTER.png
  assets/cn/meowfficer/MEOWFFICER_GET_CHECK.png
  assets/cn/meowfficer/MEOWFFICER_SR_CHECK.png
  assets/cn/meowfficer/MEOWFFICER_STATUS.png
  assets/cn/meowfficer/OCR_MEOWFFICER_FEED.png
  assets/cn/meowfficer/OCR_MEOWFFICER_QUEUE.png
  assets/en/meowfficer/MEOWFFICER_CANCEL.png
  assets/en/meowfficer/MEOWFFICER_ENHANCE_CONFIRM.png
  assets/en/meowfficer/MEOWFFICER_ENHANCE_ENTER.png
  assets/en/meowfficer/MEOWFFICER_FEED_CANCEL.png
  assets/en/meowfficer/MEOWFFICER_FEED_CONFIRM.png
  assets/en/meowfficer/MEOWFFICER_FEED_ENTER.png
  assets/en/meowfficer/MEOWFFICER_GET_CHECK.png
  assets/en/meowfficer/MEOWFFICER_SR_CHECK.png
  assets/en/meowfficer/MEOWFFICER_STATUS.png
  assets/en/meowfficer/OCR_MEOWFFICER_FEED.png
  assets/en/meowfficer/OCR_MEOWFFICER_QUEUE.png
  assets/jp/meowfficer/MEOWFFICER_CANCEL.png
  assets/jp/meowfficer/MEOWFFICER_ENHANCE_CONFIRM.png
  assets/jp/meowfficer/MEOWFFICER_ENHANCE_ENTER.png
  assets/jp/meowfficer/MEOWFFICER_FEED_CANCEL.png
  assets/jp/meowfficer/MEOWFFICER_FEED_CONFIRM.png
  assets/jp/meowfficer/MEOWFFICER_FEED_ENTER.png
  assets/jp/meowfficer/MEOWFFICER_GET_CHECK.png
  assets/jp/meowfficer/MEOWFFICER_SR_CHECK.png
  assets/jp/meowfficer/MEOWFFICER_STATUS.png
  assets/jp/meowfficer/OCR_MEOWFFICER_FEED.png
  assets/jp/meowfficer/OCR_MEOWFFICER_QUEUE.png
  assets/tw/meowfficer/MEOWFFICER_CANCEL.png
  assets/tw/meowfficer/MEOWFFICER_ENHANCE_CONFIRM.png
  assets/tw/meowfficer/MEOWFFICER_ENHANCE_ENTER.png
  assets/tw/meowfficer/MEOWFFICER_FEED_CANCEL.png
  assets/tw/meowfficer/MEOWFFICER_FEED_CONFIRM.png
  assets/tw/meowfficer/MEOWFFICER_FEED_ENTER.png
  assets/tw/meowfficer/MEOWFFICER_GET_CHECK.png
  assets/tw/meowfficer/MEOWFFICER_SR_CHECK.png
  assets/tw/meowfficer/MEOWFFICER_STATUS.png
  assets/tw/meowfficer/OCR_MEOWFFICER_FEED.png
  assets/tw/meowfficer/OCR_MEOWFFICER_QUEUE.png
  config/template.json
  module/config/argument/args.json
  module/config/argument/argument.yaml
  module/config/config_generated.py
  module/config/i18n/en-US.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
  module/meowfficer/assets.py
  module/meowfficer/base.py
  module/meowfficer/buy.py
  module/meowfficer/collect.py
  module/meowfficer/enhance.py
  module/meowfficer/fort.py
  module/meowfficer/meowfficer.py
  module/meowfficer/train.py
Labels: feature, LOW priority

#940 适配 vmos pro 的adb截图
  module/device/method/adb.py
Labels: emulator issue
