Repository LmeSzinc/AzurLaneAutoScript, pull requests merged in 2022-09, with the labels that each got.

#1597 Fix:[TW]exercise QUIT_RECONFIRM.png
  assets/tw/exercise/QUIT_RECONFIRM.BUTTON.png
  assets/tw/exercise/QUIT_RECONFIRM.png
  module/exercise/assets.py
Labels: assets issue, Server: TW

#1612 Fix: Missing title and content in notify
  module/notify.py
Labels: bug

#1615 Fix: OneHitMode and call AshBeaconTask time conflicts
  assets/cn/os_ash/META_BEGIN_ENTRANCE.BUTTON.png
  assets/cn/os_ash/META_BEGIN_ENTRANCE.png
  assets/cn/os_ash/META_MAIN_DOSSIER_ENTRANCE.BUTTON.png
  assets/cn/os_ash/META_MAIN_DOSSIER_ENTRANCE.png
  assets/en/os_ash/META_BEGIN_ENTRANCE.BUTTON.png
  assets/en/os_ash/META_BEGIN_ENTRANCE.png
  assets/en/os_ash/META_MAIN_DOSSIER_ENTRANCE.BUTTON.png
  assets/en/os_ash/META_MAIN_DOSSIER_ENTRANCE.png
  assets/jp/os_ash/META_BEGIN_ENTRANCE.BUTTON.png
  assets/jp/os_ash/META_BEGIN_ENTRANCE.png
  assets/jp/os_ash/META_MAIN_DOSSIER_ENTRANCE.BUTTON.png
  assets/jp/os_ash/META_MAIN_DOSSIER_ENTRANCE.png
  assets/tw/os_ash/META_BEGIN_ENTRANCE.BUTTON.png
  assets/tw/os_ash/META_BEGIN_ENTRANCE.png
  assets/tw/os_ash/META_MAIN_DOSSIER_ENTRANCE.BUTTON.png
  assets/tw/os_ash/META_MAIN_DOSSIER_ENTRANCE.png
  module/os_ash/ash.py
  module/os_ash/assets.py
  module/os_ash/meta.py
Labels: bug

#1650 Fix: [JP]Meta begin entrance asset
  assets/jp/os_ash/META_BEGIN_ENTRANCE.gif
  assets/jp/os_ash/META_BEGIN_ENTRANCE.png
  module/os_ash/assets.py
Labels: assets issue, Server: JP

#1662 Fix: Lack of flagships' template
  module/campaign/gems_farming.py
Labels: bug

#1677 Opt: Auto handle git config corruption
  assets/en/tactical/RAPID_TRAINING.png
  deploy/git.py
  module/combat/emotion.py
  module/tactical/assets.py
Labels: bug

#1666 Add: auto-run config in deploy
  config/deploy.template-AidLux-cn.yaml
  config/deploy.template-AidLux.yaml
  config/deploy.template-cn.yaml
  config/deploy.template-docker-cn.yaml
  config/deploy.template-docker.yaml
  config/deploy.template.yaml
  deploy/config.py
  deploy/template
  module/webui/app.py
Labels: good first issue, feature

#1688 Add: ServerChecker support for Server JP
  module/config/argument/args.json
  module/config/config_generated.py
  module/config/i18n/en-US.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
  module/config/server.py
Labels: feature, Server: JP
