Repository LmeSzinc/AzurLaneAutoScript, pull requests merged in 2022-11, with the labels that each got.

#1806 Fix: Config save to wrong file when switch config
  module/webui/app.py
Labels: bug

#1811 Upd: [TW] MISSION_MONTHLY_BOSS
  assets/tw/os_handler/MISSION_MONTHLY_BOSS.png
  module/os_handler/assets.py
Labels: assets issue, Server: TW

#1821 Fix: Verify filename when adding new config
  module/config/i18n/en-US.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
  module/submodule/submodule.py
  module/submodule/utils.py
  module/webui/app.py
  submodule/AlasMaaBridge/module/config/config.py
  submodule/AlasMaaBridge/module/config/config_updater.py
  submodule/AlasMaaBridge/module/logger.py
Labels: bug

#1823 Opt: Optimized logic of MaaMaterial
  config/template.maa.json
  module/config/config_updater.py
  submodule/AlasMaaBridge/module/config/argument/args.json
  submodule/AlasMaaBridge/module/config/argument/argument.yaml
  submodule/AlasMaaBridge/module/config/argument/override.yaml
  submodule/AlasMaaBridge/module/config/config_generated.py
  submodule/AlasMaaBridge/module/config/i18n/en-US.json
  submodule/AlasMaaBridge/module/config/i18n/ja-JP.json
  submodule/AlasMaaBridge/module/config/i18n/zh-CN.json
  submodule/AlasMaaBridge/module/config/i18n/zh-TW.json
  submodule/AlasMaaBridge/module/handler/asst_backup.py
  submodule/AlasMaaBridge/module/handler/handler.py
Labels: optimization

#1832 fix:[tw]os_combat assets
  assets/tw/os_combat/SIREN_PREPARATION.png
  module/os_combat/assets.py
Labels: assets issue, Server: TW

#1830 优化了MAA插件的serial检测和自定义基建
  submodule/AlasMaaBridge/module/config/i18n/zh-CN.json
  submodule/AlasMaaBridge/module/handler/handler.py
Labels: bug, good first issue, emulator issue

#1847 Add: force_shopping_if_credit_full of MAA
  config/template.maa.json
  submodule/AlasMaaBridge/module/config/argument/args.json
  submodule/AlasMaaBridge/module/config/argument/argument.yaml
  submodule/AlasMaaBridge/module/config/argument/default.yaml
  submodule/AlasMaaBridge/module/config/argument/override.yaml
  submodule/AlasMaaBridge/module/config/config_generated.py
  submodule/AlasMaaBridge/module/config/i18n/en-US.json
  submodule/AlasMaaBridge/module/config/i18n/ja-JP.json
  submodule/AlasMaaBridge/module/config/i18n/zh-CN.json
  submodule/AlasMaaBridge/module/config/i18n/zh-TW.json
  submodule/AlasMaaBridge/module/handler/handler.py
Labels: feature

#1864 Fix: Flagship lv32 cause frequent change
  module/campaign/gems_farming.py
  module/retire/retirement.py
Labels: bug

#1870 Add: Option to skip SSL verify
  config/deploy.template-AidLux-cn.yaml
  config/deploy.template-AidLux.yaml
  config/deploy.template-cn.yaml
  config/deploy.template-docker-cn.yaml
  config/deploy.template-docker.yaml
  config/deploy.template.yaml
  deploy/config.py
  deploy/git.py
  deploy/pip.py
  deploy/template
Labels: feature

#1878 Fix: Error 10054 when install uiautomator2
  deploy/adb.py
  module/device/connection.py
Labels: bug

#1897 Opt: Update pathfinding weight_data & roadblocks
  campaign/campaign_main/campaign_7_4.py
Labels: optimization, good first issue
