Repository LmeSzinc/AzurLaneAutoScript, pull requests merged in 2022-05, with the labels that each got.

#1122 fix: meowfficer lock cancel click may has no effects
  module/meowfficer/collect.py
Labels: bug

#1117 Opt: Retire next time if material is too little
  assets/cn/retire/DOCK_AMOUNT.png
  assets/cn/retire/EMPTY_ENHANCE_SLOT.png
  assets/en/retire/DOCK_AMOUNT.png
  assets/en/retire/EMPTY_ENHANCE_SLOT.png
  assets/jp/retire/DOCK_AMOUNT.png
  assets/jp/retire/EMPTY_ENHANCE_SLOT.png
  assets/tw/retire/DOCK_AMOUNT.png
  assets/tw/retire/EMPTY_ENHANCE_SLOT.png
  module/config/i18n/en-US.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
  module/handler/assets.py
  module/retire/assets.py
  module/retire/enhancement.py
  module/retire/retirement.py
Labels: optimization

#1119 Add: new setting makes research more stable
  module/config/argument/args.json
  module/config/argument/argument.yaml
  module/config/config_generated.py
  module/config/i18n/en-US.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
  module/research/project.py
  module/research/research.py
Labels: feature

#1123 feat: meowfficer talent screenshot & upload
  assets/cn/meowfficer/MEOWFFICER_TALENT_CLOSE.png
  assets/en/meowfficer/MEOWFFICER_TALENT_CLOSE.png
  assets/jp/meowfficer/MEOWFFICER_TALENT_CLOSE.png
  assets/tw/meowfficer/MEOWFFICER_TALENT_CLOSE.png
  config/template.json
  module/config/argument/args.json
  module/config/argument/argument.yaml
  module/config/config_generated.py
  module/config/i18n/en-US.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
  module/meowfficer/assets.py
  module/meowfficer/collect.py
Labels: feature

#1127 Deployment: Add dockerfile for arm64
  dev_tools/arm64/Dockerfile
  dev_tools/arm64/requirements.txt
Labels: good first issue, dependencies

#1136 Opt: Combined save and upload options
  config/template.json
  module/combat/combat.py
  module/commission/commission.py
  module/config/argument/args.json
  module/config/argument/argument.yaml
  module/config/config_generated.py
  module/config/config_updater.py
  module/config/i18n/en-US.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
  module/config/redirect_utils/utils.py
  module/handler/mystery.py
  module/map/map_operation.py
  module/meowfficer/buy.py
  module/meowfficer/collect.py
  module/os/fleet.py
  module/os/map.py
  module/research/research.py
  module/statistics/azurstats.py
Labels: optimization

#1159 Add: more research preset
  module/config/argument/args.json
  module/config/argument/argument.yaml
  module/config/config_generated.py
  module/config/i18n/en-US.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
  module/research/preset.py
Labels: good first issue, feature
