Repository LmeSzinc/AzurLaneAutoScript, pull requests merged in 2022-04, with the labels that each got.

#997 Fix: reconnect when device offline
  module/device/method/utils.py
Labels: optimization, good first issue, emulator issue

#1002 add newline standard to LF
  .gitattributes
Labels: optimization

#1004 Add Ashen Simulacrum WarArchives
  assets/cn/war_archives/TEMPLATE_ASHEN_SIMULACRUM.png
  assets/cn/war_archives/TEMPLATE_SCHERZO_OF_IRON_AND_BLOOD.png
  campaign/Readme.md
  campaign/war_archives_20200820_cn/a1.py
  campaign/war_archives_20200820_cn/a2.py
  campaign/war_archives_20200820_cn/a3.py
  campaign/war_archives_20200820_cn/b1.py
  campaign/war_archives_20200820_cn/b2.py
  campaign/war_archives_20200820_cn/b3.py
  campaign/war_archives_20200820_cn/c1.py
  campaign/war_archives_20200820_cn/c2.py
  campaign/war_archives_20200820_cn/c3.py
  campaign/war_archives_20200820_cn/d1.py
  campaign/war_archives_20200820_cn/d2.py
  campaign/war_archives_20200820_cn/d3.py
  campaign/war_archives_20200820_cn/sp.py
  campaign/war_archives_20210325_cn/a1.py
  campaign/war_archives_20210325_cn/a2.py
  campaign/war_archives_20210325_cn/a3.py
  campaign/war_archives_20210325_cn/as1.py
  campaign/war_archives_20210325_cn/as2.py
  campaign/war_archives_20210325_cn/b1.py
  campaign/war_archives_20210325_cn/b2.py
  campaign/war_archives_20210325_cn/b3.py
  campaign/war_archives_20210325_cn/bs1.py
  campaign/war_archives_20210325_cn/bs2.py
  campaign/war_archives_20210325_cn/c1.py
  campaign/war_archives_20210325_cn/c2.py
  campaign/war_archives_20210325_cn/c3.py
  campaign/war_archives_20210325_cn/campaign_base.py
  campaign/war_archives_20210325_cn/cs1.py
  campaign/war_archives_20210325_cn/cs2.py
  campaign/war_archives_20210325_cn/d1.py
  campaign/war_archives_20210325_cn/d2.py
  campaign/war_archives_20210325_cn/d3.py
  campaign/war_archives_20210325_cn/ds1.py
  campaign/war_archives_20210325_cn/ds2.py
  module/config/argument/args.json
  module/config/i18n/en-US.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/war_archives/assets.py
  module/war_archives/dictionary.py
Labels: good first issue, feature

#963 Opt: Refactor module enhancement
  assets/cn/handler/EMPTY_ENHANCE_SLOT.png
  assets/en/handler/EMPTY_ENHANCE_SLOT.png
  assets/jp/handler/EMPTY_ENHANCE_SLOT.png
  assets/tw/handler/EMPTY_ENHANCE_SLOT.png
  module/base/button.py
  module/base/template.py
  module/handler/assets.py
  module/retire/enhancement.py
Labels: optimization, good first issue

#1047 Opt: AutoSearchFleetOrder is merged into FleetOrder
  assets/gui/css/alas.css
  config/template.json
  module/combat/emotion.py
  module/config/argument/args.json
  module/config/argument/argument.yaml
  module/config/argument/override.yaml
  module/config/config_generated.py
  module/config/i18n/en-US.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
  module/handler/fast_forward.py
  module/hard/hard.py
  module/map/map_operation.py
Labels: optimization

#1061 台服指揮喵訓練圖片修正
  assets/tw/meowfficer/MEOWFFICER_APPLY_LOCK.png
  assets/tw/meowfficer/MEOWFFICER_APPLY_UNLOCK.png
  assets/tw/meowfficer/MEOWFFICER_CANCEL.png
  assets/tw/meowfficer/MEOWFFICER_ENHANCE_CONFIRM.png
  assets/tw/meowfficer/MEOWFFICER_FEED_CANCEL.png
  assets/tw/meowfficer/MEOWFFICER_FEED_CONFIRM.png
  assets/tw/meowfficer/MEOWFFICER_PURPLE_CHECK.png
  module/meowfficer/assets.py
Labels: assets issue, Server: TW
