Repository LmeSzinc/AzurLaneAutoScript, pull requests merged in 2022-03, with the labels that each got.

#948 Upd: meowfficer re-work allow retention of gold and purple meowfficer
  assets/cn/meowfficer/MEOWFFICER_APPLY_LOCK.png
  assets/cn/meowfficer/MEOWFFICER_APPLY_UNLOCK.png
  assets/cn/meowfficer/MEOWFFICER_GOLD_CHECK.png
  assets/cn/meowfficer/MEOWFFICER_PURPLE_CHECK.png
  assets/en/meowfficer/MEOWFFICER_APPLY_LOCK.png
  assets/en/meowfficer/MEOWFFICER_APPLY_UNLOCK.png
  assets/en/meowfficer/MEOWFFICER_GOLD_CHECK.png
  assets/en/meowfficer/MEOWFFICER_PURPLE_CHECK.png
  assets/jp/meowfficer/MEOWFFICER_APPLY_LOCK.png
  assets/jp/meowfficer/MEOWFFICER_APPLY_UNLOCK.png
  assets/jp/meowfficer/MEOWFFICER_GOLD_CHECK.png
  assets/jp/meowfficer/MEOWFFICER_PURPLE_CHECK.png
  assets/tw/meowfficer/MEOWFFICER_APPLY_LOCK.png
  assets/tw/meowfficer/MEOWFFICER_APPLY_UNLOCK.png
  assets/tw/meowfficer/MEOWFFICER_GOLD_CHECK.png
  assets/tw/meowfficer/MEOWFFICER_PURPLE_CHECK.png
  module/config/argument/args.json
  module/config/argument/argument.yaml
  module/config/config_generated.py
  module/config/i18n/en-US.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
  module/meowfficer/assets.py
  module/meowfficer/collect.py
  module/meowfficer/train.py
Labels: feature

#962 Upd: [TW] Update dorm assets
  assets/tw/dorm/DORM_FEED_CHECK.png
  assets/tw/dorm/DORM_FEED_ENTER.png
Labels: good first issue, assets issue

#965 Opt: Standalone OCR service
  config/deploy.template-AidLux-cn.yaml
  config/deploy.template-AidLux.yaml
  config/deploy.template-cn.yaml
  config/deploy.template.yaml
  deploy/template
  module/ocr/models.py
  module/ocr/ocr.py
  module/ocr/rpc.py
  module/webui/app.py
  requirements-in.txt
  requirements.txt
Labels: optimization, python

#975 Fix: Improved the logic of getting package name on WSA
  module/device/app_control.py
  module/device/connection.py
  module/device/device.py
  module/device/method/wsa.py
Labels: optimization

#985 Fix: The behavior of saving the configuration will be atomic
  .gitignore
  deploy/AidLux/0.92/requirements.txt
  module/config/utils.py
  requirements-in.txt
  requirements.txt
Labels: optimization
