Repository LmeSzinc/AzurLaneAutoScript, pull requests merged in 2022-07, with the labels that each got.

#1280 Fix: [TW] raid_ticket_use_confirm assets
  assets/tw/raid/TICKET_USE_CONFIRM.BUTTON.png
  assets/tw/raid/TICKET_USE_CONFIRM.png
  module/raid/assets.py
Labels: assets issue, Server: TW

#1314 Fix: add T4 to book filter
  module/tactical/tactical_class.py
Labels: bug, good first issue

#1344 Upd: [JP] BEACON_ENTER
  assets/jp/os_ash/BEACON_ENTER.BUTTON.png
  assets/jp/os_ash/BEACON_ENTER.png
  module/os_ash/assets.py
Labels: assets issue, Server: JP

#1349 Upd: [CN] BUILD_CUBE_COUNT
  assets/cn/gacha/BUILD_CUBE_COUNT.png
  module/gacha/assets.py
Labels: assets issue, Server: CN

#1355 Fix: [JP] BEACON_EMPTY
  assets/jp/os_ash/BEACON_EMPTY.png
  module/os_ash/assets.py
Labels: assets issue, Server: JP

#1352 Add: Use build tickets for event pool
  assets/cn/gacha/BUILD_TICKET_COUNT.png
  config/template.json
  module/config/argument/args.json
  module/config/argument/argument.yaml
  module/config/config_generated.py
  module/config/i18n/en-US.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
  module/gacha/assets.py
  module/gacha/gacha_reward.py
Labels: feature

#1377 Fix: [JP] Research assets
  assets/jp/research/QUEUE_CHECK.png
  assets/jp/research/QUEUE_CLAIM_REWARD.png
  assets/jp/research/QUEUE_REMAIN.png
  assets/jp/research/RESEARCH_QUEUE_ADD.png
  assets/jp/research/RESEARCH_START.png
  assets/jp/research/RESEARCH_STOP.png
  assets/jp/research/TEMPLATE_DETAIL.png
  assets/jp/research/TEMPLATE_RUNNING.png
  assets/jp/research/TEMPLATE_WAITING.png
  module/research/assets.py
  module/research/research.py
  module/research/rqueue.py
Labels: assets issue, Server: JP

#1390 Add: [JP] Research S5 assets
  assets/research_blueprint/brest.png
  assets/research_blueprint/chkalov.png
  assets/research_blueprint/harbin.png
  assets/research_blueprint/plymouth.png
  assets/research_blueprint/rupprecht.png
Labels: good first issue, assets issue, Server: JP

#1386 add war archive: Swirling Cherry Blossoms
  README.md
  assets/cn/gacha/BUILD_CUBE_COUNT.png
  assets/cn/war_archives/TEMPLATE_SWIRLING_CHERRY_BLOSSOMS.png
  assets/jp/os_ash/BEACON_EMPTY.png
  assets/jp/os_ash/BEACON_ENTER.BUTTON.png
  assets/jp/os_ash/BEACON_ENTER.png
  assets/jp/research/QUEUE_CHECK.png
  assets/jp/research/QUEUE_CLAIM_REWARD.png
  assets/jp/research/QUEUE_REMAIN.png
  assets/jp/research/RESEARCH_QUEUE_ADD.png
  assets/jp/research/RESEARCH_START.png
  assets/jp/research/RESEARCH_STOP.png
  assets/jp/research/RESEARCH_UNAVAILABLE.png
  assets/jp/research/TEMPLATE_DETAIL.png
  assets/jp/research/TEMPLATE_RUNNING.png
  assets/jp/research/TEMPLATE_WAITING.png
  assets/jp/supply_pack/BUY_CONFIRM.png
  assets/tw/os_ash/BEACON_EMPTY.png
  assets/tw/os_ash/BEACON_ENTER.png
  campaign/Readme.md
  campaign/campaign_main/campaign_9_1.py
  campaign/war_archives_20210624_cn/a1.py
  campaign/war_archives_20210624_cn/a2.py
  campaign/war_archives_20210624_cn/a3.py
  campaign/war_archives_20210624_cn/b1.py
  campaign/war_archives_20210624_cn/b2.py
  campaign/war_archives_20210624_cn/b3.py
  campaign/war_archives_20210624_cn/c1.py
  campaign/war_archives_20210624_cn/c2.py
  campaign/war_archives_20210624_cn/c3.py
  campaign/war_archives_20210624_cn/d1.py
  campaign/war_archives_20210624_cn/d2.py
  campaign/war_archives_20210624_cn/d3.py
  module/config/argument/args.json
  module/config/i18n/en-US.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
  module/gacha/assets.py
  module/ocr/ocr.py
  module/os_ash/assets.py
  module/research/assets.py
  module/research/research.py
  module/research/rqueue.py
  module/shop/shop_guild.py
  module/supply_pack/assets.py
  module/war_archives/assets.py
  module/war_archives/dictionary.py
Labels: feature

#1381 Opt: Give up research intelligently when resources not enough
  config/template.json
  module/config/argument/args.json
  module/config/argument/argument.yaml
  module/config/config_generated.py
  module/config/i18n/en-US.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
  module/research/project.py
  module/research/research.py
  module/research/rqueue.py
Labels: feature

#1417 Opt: Cancel the function of delaying research when reset is unavailable
  module/config/i18n/en-US.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
  module/research/research.py
Labels: bug

#1413 Upd: [TW] Research_queue_*.assets
  assets/tw/research/QUEUE_CHECK.png
  assets/tw/research/QUEUE_CLAIM_REWARD.png
  assets/tw/research/QUEUE_REMAIN.png
  assets/tw/research/RESEARCH_QUEUE_ADD.png
  assets/tw/research/RESEARCH_START.png
  assets/tw/research/RESEARCH_STOP.png
  assets/tw/research/TEMPLATE_DETAIL.png
  assets/tw/research/TEMPLATE_RUNNING.png
  assets/tw/research/TEMPLATE_WAITING.png
  module/research/assets.py
  module/research/research.py
  module/research/rqueue.py
Labels: assets issue, Server: TW

#1400 Add: Submarine supports in GemsFarming;EnemyFilter in SOS;Replace old EventAb and Cd with individual EventABCD
  alas.py
  campaign/campaign_sos/campaign_10_5.py
  campaign/campaign_sos/campaign_3_5.py
  campaign/campaign_sos/campaign_4_5.py
  campaign/campaign_sos/campaign_5_5.py
  campaign/campaign_sos/campaign_6_5.py
  campaign/campaign_sos/campaign_7_5.py
  campaign/campaign_sos/campaign_8_5.py
  campaign/campaign_sos/campaign_9_5.py
  campaign/campaign_sos/campaign_base.py
  config/template.json
  module/campaign/campaign_event.py
  module/campaign/gems_farming.py
  module/config/argument/args.json
  module/config/argument/argument.yaml
  module/config/argument/default.yaml
  module/config/argument/menu.json
  module/config/argument/override.yaml
  module/config/argument/task.yaml
  module/config/config_generated.py
  module/config/config_manual.py
  module/config/config_updater.py
  module/config/i18n/en-US.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
  module/event/campaign_abcd.py
  module/event/campaign_cd.py
Labels: feature

#1441 Opt: Change"UseU522Skill" into "UseOpenOceanSupport"
  module/config/argument/args.json
  module/config/argument/argument.yaml
  module/config/config_generated.py
  module/config/i18n/en-US.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
  module/map/fleet.py
Labels: optimization

#1452 fix:[TW]GET_ITEMS_3.png
  assets/tw/combat/GET_ITEMS_3.png
  module/combat/assets.py
  module/config/i18n/en-US.json
  module/research/rqueue.py
Labels: assets issue, Server: TW

#1457 Fix: Wrong step number while 'fleets_reversed' is True
  module/map/fleet.py
Labels: bug, good first issue

#1454 Fix: Clear shell warnings with loose match
  module/device/method/utils.py
Labels: emulator issue
