Repository LmeSzinc/AzurLaneAutoScript, pull requests merged in 2022-10, with the labels that each got.

#1657 Add: Submodule AlasMaaBridge (experimental)
  .gitignore
  README.md
  README_en.md
  config/template.maa.json
  module/config/config.py
  module/config/config_updater.py
  module/config/utils.py
  module/device/connection_attr.py
  module/submodule/submodule.py
  module/submodule/utils.py
  module/webui/app.py
  module/webui/lang.py
  module/webui/process_manager.py
  submodule/AlasMaaBridge/maa.py
  submodule/AlasMaaBridge/module/config/argument/args.json
  submodule/AlasMaaBridge/module/config/argument/argument.yaml
  submodule/AlasMaaBridge/module/config/argument/default.yaml
  submodule/AlasMaaBridge/module/config/argument/menu.json
  submodule/AlasMaaBridge/module/config/argument/override.yaml
  submodule/AlasMaaBridge/module/config/argument/task.yaml
  submodule/AlasMaaBridge/module/config/config.py
  submodule/AlasMaaBridge/module/config/config_generated.py
  submodule/AlasMaaBridge/module/config/config_updater.py
  submodule/AlasMaaBridge/module/config/i18n/en-US.json
  submodule/AlasMaaBridge/module/config/i18n/ja-JP.json
  submodule/AlasMaaBridge/module/config/i18n/zh-CN.json
  submodule/AlasMaaBridge/module/config/i18n/zh-TW.json
  submodule/AlasMaaBridge/module/handler/handler.py
Labels: feature

#1706 Add: ActionPoint limit (#1696)
  config/template.json
  module/config/argument/args.json
  module/config/argument/argument.yaml
  module/config/config_generated.py
  module/config/config_updater.py
  module/config/i18n/en-US.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
  module/config/redirect_utils/os_handler.py
  module/os_handler/action_point.py
Labels: feature

#1727 add wararchive: Universe in Unison
  assets/cn/war_archives/TEMPLATE_UNIVERSE_IN_UNISON.png
  campaign/Readme.md
  campaign/war_archives_20201029_cn/campaign_base.py
  campaign/war_archives_20201029_cn/sp1.py
  campaign/war_archives_20201029_cn/sp2.py
  campaign/war_archives_20201029_cn/sp3.py
  campaign/war_archives_20201029_cn/sp4.py
  campaign/war_archives_20201029_cn/sp5.py
  module/config/argument/args.json
  module/config/i18n/en-US.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
  module/war_archives/assets.py
  module/war_archives/dictionary.py
Labels: event

#1739 Fix: check VanguardChange switch in GemsFarming
  module/campaign/gems_farming.py
Labels: bug

#1749 Fix: FileNotFoundError when removing git config
  deploy/git.py
Labels: bug

#1775 Upd: [TW] EQUIPMENT_OPEN and EQUIPMENT_CLOSE
  assets/tw/equipment/EQUIPMENT_CLOSE.png
  assets/tw/equipment/EQUIPMENT_OPEN.png
  module/equipment/assets.py
Labels: assets issue, Server: TW

#1609 Add: Dock scanner
  assets/cn/retire/TEMPLATE_FLEET_1.png
  assets/cn/retire/TEMPLATE_FLEET_2.png
  assets/cn/retire/TEMPLATE_FLEET_3.png
  assets/cn/retire/TEMPLATE_FLEET_4.png
  assets/cn/retire/TEMPLATE_FLEET_5.png
  assets/cn/retire/TEMPLATE_FLEET_6.png
  assets/cn/retire/TEMPLATE_IN_BATTLE.png
  assets/cn/retire/TEMPLATE_IN_COMMISSION.png
  module/campaign/gems_farming.py
  module/config/i18n/en-US.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
  module/retire/assets.py
  module/retire/dock.py
  module/retire/retirement.py
  module/retire/scanner.py
Labels: optimization

#1797 Opt: More accurate fleet scan
  module/base/template.py
  module/retire/scanner.py
Labels: optimization
