Repository LmeSzinc/AzurLaneAutoScript, pull requests merged in 2022-12, with the labels that each got.

#1863 Add: Frame of preset commission filter
  config/template.json
  module/commission/commission.py
  module/commission/preset.py
  module/commission/project.py
  module/config/argument/args.json
  module/config/argument/argument.yaml
  module/config/config_generated.py
  module/config/config_updater.py
  module/config/i18n/en-US.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
  module/research/selector.py
Labels: feature

#1891 Add new wararchives 20221117
  assets/cn/war_archives/TEMPLATE_MICROLAYER_MEDLEY.png
  assets/cn/war_archives/TEMPLATE_STARS_OF_THE_SHIMMERING_FJORD.png
  campaign/Readme.md
  campaign/war_archives_20200903_cn/campaign_base.py
  campaign/war_archives_20200903_cn/sp0.py
  campaign/war_archives_20200903_cn/sp1.py
  campaign/war_archives_20200903_cn/sp2.py
  campaign/war_archives_20200903_cn/sp3.py
  campaign/war_archives_20210819_cn/a1.py
  campaign/war_archives_20210819_cn/a2.py
  campaign/war_archives_20210819_cn/a3.py
  campaign/war_archives_20210819_cn/b1.py
  campaign/war_archives_20210819_cn/b2.py
  campaign/war_archives_20210819_cn/b3.py
  campaign/war_archives_20210819_cn/c1.py
  campaign/war_archives_20210819_cn/c2.py
  campaign/war_archives_20210819_cn/c3.py
  campaign/war_archives_20210819_cn/d1.py
  campaign/war_archives_20210819_cn/d2.py
  campaign/war_archives_20210819_cn/d3.py
  module/config/argument/args.json
  module/config/i18n/en-US.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
  module/war_archives/assets.py
  module/war_archives/dictionary.py
Labels: event

#1923 Add: Support OS Voucher Shop
  alas.py
  assets/cn/os_handler/EXCHANGE_ENTER.png
  assets/cn/shop/SHOP_VOUCHER.png
  assets/cn/shop/VOUCHER_SHOP_SCROLL_AREA.png
  assets/en/os_handler/EXCHANGE_ENTER.png
  assets/en/shop/SHOP_VOUCHER.png
  assets/en/shop/VOUCHER_SHOP_SCROLL_AREA.png
  assets/jp/shop/SHOP_VOUCHER.png
  assets/jp/shop/VOUCHER_SHOP_SCROLL_AREA.png
  assets/shop/cost/Voucher.png
  assets/shop/voucher/BookBlueT4.png
  assets/shop/voucher/BookRedT4.png
  assets/shop/voucher/BookYellowT4.png
  assets/shop/voucher/Coin.png
  assets/shop/voucher/HECombatPlan.png
  assets/shop/voucher/LoggerAbyssalT5.png
  assets/shop/voucher/LoggerAbyssalT6.png
  assets/shop/voucher/LoggerArchiveT2.png
  assets/shop/voucher/LoggerArchiveT3.png
  assets/shop/voucher/LoggerObscureT5.png
  assets/shop/voucher/LoggerObscureT6.png
  assets/shop/voucher/TuningCombatT2.png
  assets/shop/voucher/TuningOffenseT2.png
  assets/shop/voucher/TuningSurvivalT2.png
  assets/tw/shop/SHOP_VOUCHER.png
  assets/tw/shop/VOUCHER_SHOP_SCROLL_AREA.png
  config/template.json
  module/campaign/os_run.py
  module/config/argument/args.json
  module/config/argument/argument.yaml
  module/config/argument/menu.json
  module/config/argument/override.yaml
  module/config/argument/task.yaml
  module/config/config.py
  module/config/config_generated.py
  module/config/config_manual.py
  module/config/i18n/en-US.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
  module/config/redirect_utils/shop_filter.py
  module/handler/info_handler.py
  module/os/operation_siren.py
  module/os_handler/assets.py
  module/retire/retirement.py
  module/shop/assets.py
  module/shop/base.py
  module/shop/shop_medal.py
  module/shop/shop_voucher.py
Labels: feature

#1944 Fix:handler assets
  assets/tw/handler/MAP_WALK_OUT_OF_STEP.png
  assets/tw/template/TEMPLATE_MAP_WALK_OUT_OF_STEP.png
  module/handler/assets.py
Labels: assets issue, Server: TW

#1941 Opt: Reconstructed hazard 1 leveling
  assets/cn/os_handler/STRATEGIC_SEARCH_DEVICE_CHECK.png
  assets/cn/os_handler/STRATEGIC_SEARCH_DEVICE_CONTINUE.png
  assets/cn/os_handler/STRATEGIC_SEARCH_DEVICE_STOP.png
  assets/cn/os_handler/STRATEGIC_SEARCH_MAP_OPTION_OFF.png
  assets/cn/os_handler/STRATEGIC_SEARCH_MERCHANT_CONTINUE.png
  assets/cn/os_handler/STRATEGIC_SEARCH_MERCHANT_STOP.png
  assets/cn/os_handler/STRATEGIC_SEARCH_POPUP_CHECK.png
  assets/cn/os_handler/STRATEGIC_SEARCH_SCROLL_AREA.png
  assets/cn/os_handler/STRATEGIC_SEARCH_SECURED_OPTION_OFF.BUTTON.png
  assets/cn/os_handler/STRATEGIC_SEARCH_SECURED_OPTION_OFF.png
  assets/cn/os_handler/STRATEGIC_SEARCH_SECURED_OPTION_ON.png
  assets/cn/os_handler/STRATEGIC_SEARCH_SUBMIT_OFF.png
  assets/cn/os_handler/STRATEGIC_SEARCH_SUBMIT_ON.png
  assets/cn/os_handler/STRATEGIC_SEARCH_ZONE_MODE_RANDOM.png
  assets/cn/os_handler/STRATEGIC_SEARCH_ZONE_MODE_REPEAT.png
  config/template.json
  module/config/argument/args.json
  module/config/argument/argument.yaml
  module/config/config_generated.py
  module/config/i18n/en-US.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
  module/os/map.py
  module/os/operation_siren.py
  module/os_handler/assets.py
  module/os_handler/map_event.py
  module/os_handler/strategic.py
Labels: optimization

#1949 Add: [JP] asset support for ship scan
  assets/jp/retire/TEMPLATE_FLEET_1.png
  assets/jp/retire/TEMPLATE_FLEET_2.png
  assets/jp/retire/TEMPLATE_FLEET_3.png
  assets/jp/retire/TEMPLATE_FLEET_4.png
  assets/jp/retire/TEMPLATE_FLEET_5.png
  assets/jp/retire/TEMPLATE_FLEET_6.png
  assets/jp/retire/TEMPLATE_IN_BATTLE.png
  assets/jp/retire/TEMPLATE_IN_COMMISSION.png
  module/campaign/gems_farming.py
  module/retire/assets.py
  module/retire/retirement.py
Labels: assets issue / 资源适配问题, Server: JP / 日服

#1950 Add: [JP] asset support for voucher shop
  assets/jp/os_handler/EXCHANGE_ENTER.png
  module/campaign/os_run.py
  module/os_handler/assets.py
  module/shop/shop_voucher.py
Labels: assets issue / 资源适配问题, Server: JP / 日服

#1958 Fix: Unable to handle option in STRATEGIC_SEARCH_POPUP_CHECK
  assets/cn/os_handler/STRATEGIC_SEARCH_SUBMIT_CHECK.png
  module/os_handler/assets.py
  module/os_handler/strategic.py
Labels: bug / 缺陷

#1961 Add: [CN] asset support for strategic search
  assets/cn/os_handler/STRATEGIC_SEARCH_DEVICE_CHECK.png
  assets/cn/os_handler/STRATEGIC_SEARCH_DEVICE_CONTINUE.png
  assets/cn/os_handler/STRATEGIC_SEARCH_DEVICE_STOP.png
  assets/cn/os_handler/STRATEGIC_SEARCH_MERCHANT_CONTINUE.png
  assets/cn/os_handler/STRATEGIC_SEARCH_MERCHANT_STOP.png
  assets/cn/os_handler/STRATEGIC_SEARCH_SECURED_OPTION_OFF.BUTTON.png
  assets/cn/os_handler/STRATEGIC_SEARCH_SECURED_OPTION_OFF.png
  assets/cn/os_handler/STRATEGIC_SEARCH_SECURED_OPTION_ON.png
  assets/cn/os_handler/STRATEGIC_SEARCH_SUBMIT_CHECK.png
  assets/cn/os_handler/STRATEGIC_SEARCH_SUBMIT_OFF.png
  assets/cn/os_handler/STRATEGIC_SEARCH_SUBMIT_ON.png
  assets/cn/os_handler/STRATEGIC_SEARCH_TAB_SECURED.png
  assets/cn/os_handler/STRATEGIC_SEARCH_ZONEMODE_RANDOM.png
  assets/cn/os_handler/STRATEGIC_SEARCH_ZONEMODE_REPEAT.png
  assets/cn/os_handler/STRATEGIC_SEARCH_ZONE_MODE_RANDOM.png
  assets/cn/os_handler/STRATEGIC_SEARCH_ZONE_MODE_REPEAT.png
  module/os_handler/assets.py
  module/os_handler/strategic.py
Labels: assets issue / 资源适配问题

#1966 Add: Multiple server support of MAA
  config/template.maa.json
  submodule/AlasMaaBridge/maa.py
  submodule/AlasMaaBridge/module/config/argument/args.json
  submodule/AlasMaaBridge/module/config/argument/argument.yaml
  submodule/AlasMaaBridge/module/config/argument/override.yaml
  submodule/AlasMaaBridge/module/config/config_generated.py
  submodule/AlasMaaBridge/module/config/i18n/en-US.json
  submodule/AlasMaaBridge/module/config/i18n/ja-JP.json
  submodule/AlasMaaBridge/module/config/i18n/zh-CN.json
  submodule/AlasMaaBridge/module/config/i18n/zh-TW.json
  submodule/AlasMaaBridge/module/handler/handler.py
Labels: optimization / 优化

#1968 Fix: Threshold adjust for TEMPLATE_FLEET_4
  module/retire/scanner.py
Labels: bug / 缺陷

#1969 Fix: Regard all exception as failure
  module/server_checker.py
Labels: bug / 缺陷

#1973 Opt: Improve robustness of strategic search
  module/os_handler/strategic.py
Labels: bug / 缺陷

#1972 Add: [JP]Assets update for strategic search
  assets/jp/os_handler/ACTION_POINT_REMAIN_OS.png
  assets/jp/os_handler/STRATEGIC_SEARCH_DEVICE_CHECK.png
  assets/jp/os_handler/STRATEGIC_SEARCH_DEVICE_CONTINUE.png
  assets/jp/os_handler/STRATEGIC_SEARCH_DEVICE_STOP.png
  assets/jp/os_handler/STRATEGIC_SEARCH_MAP_OPTION_OFF.png
  assets/jp/os_handler/STRATEGIC_SEARCH_MERCHANT_CONTINUE.png
  assets/jp/os_handler/STRATEGIC_SEARCH_MERCHANT_STOP.png
  assets/jp/os_handler/STRATEGIC_SEARCH_POPUP_CHECK.png
  assets/jp/os_handler/STRATEGIC_SEARCH_SCROLL_AREA.png
  assets/jp/os_handler/STRATEGIC_SEARCH_SUBMIT_CHECK.png
  assets/jp/os_handler/STRATEGIC_SEARCH_SUBMIT_OFF.png
  assets/jp/os_handler/STRATEGIC_SEARCH_SUBMIT_ON.png
  assets/jp/os_handler/STRATEGIC_SEARCH_TAB_SECURED.png
  assets/jp/os_handler/STRATEGIC_SEARCH_ZONEMODE_RANDOM.png
  assets/jp/os_handler/STRATEGIC_SEARCH_ZONEMODE_REPEAT.png
  module/campaign/os_run.py
  module/os_handler/assets.py
Labels: assets issue / 资源适配问题, Server: JP / 日服

#1975 Upd: [TW] Mail collect
  assets/tw/freebies/MAIL_COLLECT.png
  assets/tw/freebies/MAIL_COLLECTED.png
  assets/tw/freebies/MAIL_DELETE.png
  module/freebies/assets.py
  module/freebies/freebies.py
Labels: assets issue / 资源适配问题, Server: TW / 台服

#1980 Add: re-instate Opsi Archive task
  assets/shop/voucher/LoggerUnlockT1.png
  assets/shop/voucher/LoggerUnlockT2.png
  config/template.json
  module/config/argument/args.json
  module/config/argument/argument.yaml
  module/config/argument/menu.json
  module/config/argument/override.yaml
  module/config/argument/task.yaml
  module/config/config.py
  module/config/config_generated.py
  module/config/config_manual.py
  module/config/i18n/en-US.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
  module/config/redirect_utils/shop_filter.py
  module/config/utils.py
  module/os/operation_siren.py
  module/shop/base.py
Labels: feature request / 功能请求

#1982 Add: [TW] asset support for voucher shop
  assets/tw/os_handler/EXCHANGE_CHECK.png
  assets/tw/os_handler/EXCHANGE_ENTER.png
  module/campaign/os_run.py
  module/os_handler/assets.py
  module/shop/shop_voucher.py
Labels: assets issue / 资源适配问题, Server: TW / 台服

#1986 Opt: Adjusted logic of strategic search
  module/os_handler/strategic.py
Labels: bug / 缺陷

#1992 Add: OpSi Archive Zones
  assets/gui/css/alas.css
  assets/shop/voucher/LoggerUnlockT1.png
  assets/shop/voucher/LoggerUnlockT2.png
  assets/tw/freebies/MAIL_COLLECT.png
  assets/tw/freebies/MAIL_COLLECTED.png
  assets/tw/freebies/MAIL_DELETE.png
  config/template.json
  deploy/config.py
  module/config/argument/args.json
  module/config/argument/argument.yaml
  module/config/argument/menu.json
  module/config/argument/override.yaml
  module/config/argument/task.yaml
  module/config/config.py
  module/config/config_generated.py
  module/config/config_manual.py
  module/config/i18n/en-US.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
  module/config/redirect_utils/shop_filter.py
  module/config/utils.py
  module/freebies/assets.py
  module/freebies/freebies.py
  module/os/operation_siren.py
  module/os_handler/strategic.py
  module/shop/base.py
  module/webui/app.py
Labels: feature request / 功能请求

#1993 Add: asset update for strategic search
  assets/en/os_handler/STRATEGIC_SEARCH_DEVICE_CHECK.png
  assets/en/os_handler/STRATEGIC_SEARCH_DEVICE_CONTINUE.png
  assets/en/os_handler/STRATEGIC_SEARCH_DEVICE_STOP.png
  assets/en/os_handler/STRATEGIC_SEARCH_MAP_OPTION_OFF.png
  assets/en/os_handler/STRATEGIC_SEARCH_MERCHANT_CONTINUE.png
  assets/en/os_handler/STRATEGIC_SEARCH_MERCHANT_STOP.png
  assets/en/os_handler/STRATEGIC_SEARCH_POPUP_CHECK.png
  assets/en/os_handler/STRATEGIC_SEARCH_SCROLL_AREA.png
  assets/en/os_handler/STRATEGIC_SEARCH_SUBMIT_CHECK.png
  assets/en/os_handler/STRATEGIC_SEARCH_SUBMIT_OFF.png
  assets/en/os_handler/STRATEGIC_SEARCH_SUBMIT_ON.png
  assets/en/os_handler/STRATEGIC_SEARCH_TAB_SECURED.png
  assets/en/os_handler/STRATEGIC_SEARCH_ZONEMODE_RANDOM.png
  assets/en/os_handler/STRATEGIC_SEARCH_ZONEMODE_REPEAT.png
  module/campaign/os_run.py
  module/config/config.py
  module/os_handler/assets.py
Labels: assets issue / 资源适配问题

#1994 Fix: Handle in_globe in interrupt_auto_search caused by bug
  module/os/map.py
Labels: bug / 缺陷

#2000 bug_fix:修复了作战档案红染的参访者进图找不到舰队的问题
  campaign/war_archives_20190321_en/a1.py
  campaign/war_archives_20190321_en/a3.py
  campaign/war_archives_20190321_en/c1.py
  campaign/war_archives_20190321_en/c3.py
Labels: good first issue / 首次贡献, game event / 游戏活动

#2006 Upd: Support of MAA v4.8.0
  config/template.maa.json
  submodule/AlasMaaBridge/maa.py
  submodule/AlasMaaBridge/module/config/argument/args.json
  submodule/AlasMaaBridge/module/config/argument/menu.json
  submodule/AlasMaaBridge/module/config/argument/task.yaml
  submodule/AlasMaaBridge/module/config/i18n/en-US.json
  submodule/AlasMaaBridge/module/config/i18n/ja-JP.json
  submodule/AlasMaaBridge/module/config/i18n/zh-CN.json
  submodule/AlasMaaBridge/module/config/i18n/zh-TW.json
  submodule/AlasMaaBridge/module/handler/asst_backup.py
  submodule/AlasMaaBridge/module/handler/handler.py
Labels: feature request / 功能请求

#2010 Fix: OSError when loading MAA
  submodule/AlasMaaBridge/module/handler/asst_backup.py
  submodule/AlasMaaBridge/module/handler/handler.py
Labels: bug / 缺陷

#2014 Fix: Reduce action points waste
  module/os_handler/action_point.py
Labels: bug / 缺陷

#2016 Fix: Wrong log when delay across task
  module/campaign/os_run.py
  module/config/config.py
  module/os/operation_siren.py
Labels: bug / 缺陷

#2018 Add event Parallel Superimposition (event_20221222_cn) chapter AC
  campaign/Readme.md
  campaign/event_20221222_cn/a1.py
  campaign/event_20221222_cn/a2.py
  campaign/event_20221222_cn/a3.py
  campaign/event_20221222_cn/c1.py
  campaign/event_20221222_cn/c2.py
  campaign/event_20221222_cn/c3.py
  campaign/event_20221222_cn/campaign_base.py
  module/config/argument/args.json
  module/config/i18n/en-US.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
Labels: game event / 游戏活动

#1976 Add:[JP]Assets update for the storage module
  assets/jp/storage/BOX_USE.BUTTON.png
  assets/jp/storage/BOX_USE.png
  assets/jp/storage/DISASSEMBLE.BUTTON.png
  assets/jp/storage/DISASSEMBLE.png
  assets/jp/storage/DISASSEMBLE_CANCEL.BUTTON.png
  assets/jp/storage/DISASSEMBLE_CANCEL.png
  assets/jp/storage/DISASSEMBLE_CONFIRM.BUTTON.png
  assets/jp/storage/DISASSEMBLE_CONFIRM.png
  assets/jp/storage/DISASSEMBLE_POPUP_CONFIRM.BUTTON.png
  assets/jp/storage/DISASSEMBLE_POPUP_CONFIRM.png
  assets/jp/storage/EQUIPMENT_ENTER.BUTTON.png
  assets/jp/storage/EQUIPMENT_ENTER.png
  assets/jp/storage/EQUIPMENT_FILTER.BUTTON.png
  assets/jp/storage/EQUIPMENT_FILTER.png
  assets/jp/storage/EQUIPMENT_FILTER_CONFIRM.BUTTON.png
  assets/jp/storage/EQUIPMENT_FILTER_CONFIRM.png
  assets/jp/storage/EQUIPMENT_FULL.BUTTON.png
  assets/jp/storage/EQUIPMENT_FULL.png
  assets/jp/storage/MATERIAL_CHECK.png
  assets/jp/storage/MATERIAL_ENTER.BUTTON.png
  assets/jp/storage/MATERIAL_ENTER.png
  assets/jp/ui/STORAGE_CHECK.png
  module/research/selector.py
  module/storage/assets.py
  module/ui/assets.py
Labels: assets issue / 资源适配问题, Server: JP / 日服

#1991 Opsi month boss
  alas.py
  assets/cn/os_handler/OS_ADAPTABILITY_ATTACK.png
  assets/cn/os_handler/OS_ADAPTABILITY_DURABILITY.png
  assets/cn/os_handler/OS_ADAPTABILITY_RECOVER.png
  assets/cn/os_handler/OS_MONTHBOSS_EASY.png
  assets/cn/os_handler/OS_MONTHBOSS_HARD.png
  assets/jp/os_ash/META_BEGIN_ENTRANCE.gif
  assets/tw/os_handler/STRATEGIC_SEARCH_TAB_SECURED.png
  config/template.json
  module/campaign/os_run.py
  module/config/argument/args.json
  module/config/argument/argument.yaml
  module/config/argument/menu.json
  module/config/argument/task.yaml
  module/config/config.py
  module/config/config_generated.py
  module/config/config_manual.py
  module/config/i18n/en-US.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
  module/device/connection.py
  module/os/fleet.py
  module/os/operation_siren.py
  module/os_handler/action_point.py
  module/os_handler/assets.py
Labels: feature request / 功能请求

#2047 Add: Support of touch method for MAA
  config/template.maa.json
  submodule/AlasMaaBridge/maa.py
  submodule/AlasMaaBridge/module/config/argument/args.json
  submodule/AlasMaaBridge/module/config/argument/argument.yaml
  submodule/AlasMaaBridge/module/config/config_generated.py
  submodule/AlasMaaBridge/module/config/i18n/en-US.json
  submodule/AlasMaaBridge/module/config/i18n/ja-JP.json
  submodule/AlasMaaBridge/module/config/i18n/zh-CN.json
  submodule/AlasMaaBridge/module/config/i18n/zh-TW.json
  submodule/AlasMaaBridge/module/handler/asst_backup.py
  submodule/AlasMaaBridge/module/handler/handler.py
Labels: feature request / 功能请求, Submodule: MAA / MAA插件
