Repository LmeSzinc/AzurLaneAutoScript, pull requests merged in 2023-05, with the labels that each got.

#2551 Fix: Redundant `template-maa.maa.json` config file
  module/config/config.py
  module/config/i18n/en-US.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
  module/webui/app.py
Labels: bug / 缺陷

#2559 Doc: add game settings
  README_en.md
Labels: documentation / 文档, Server: EN / EN服

#2544 Add: Dossier Meta Reward Receive (#2353)
  assets/cn/template/TEMPLATE_META_DOCK_RED_DOT.png
  assets/en/template/TEMPLATE_META_DOCK_RED_DOT.png
  assets/jp/template/TEMPLATE_META_DOCK_RED_DOT.png
  assets/tw/template/TEMPLATE_META_DOCK_RED_DOT.png
  module/meta_reward/meta_reward.py
  module/os_ash/meta.py
  module/template/assets.py
Labels: feature request / 功能请求

#2568 Fix: Skip main task of hard mode when remaining number of times is 0
  module/campaign/run.py
Labels: bug / 缺陷

#2601 Fix: Digit ocr should contain and replace 'B' to '8'
  module/ocr/ocr.py
Labels: bug / 缺陷

#2623 Upd: [JP] Shop assets
  assets/jp/shop/SHOP_CORE_SWIPE_END.png
  assets/jp/shop/SHOP_META_SWIPE_END.png
  module/shop/assets.py
Labels: assets issue / 资源适配问题, Server: JP / 日服

#2657 Fix: result of map_rescan_current passed wrongly
  module/os/map.py
Labels: bug / 缺陷

#2649 Add 'com.bilibili.blhx.bilibiliMove'
  module/config/argument/args.json
  module/config/config_generated.py
  module/config/i18n/en-US.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
  module/config/server.py
Labels: good first issue / 首次贡献, Server: CN / 国服

#2665 Fix: ActionPointPreserve reset by error
  module/os/operation_siren.py
Labels: bug / 缺陷
