Repository LmeSzinc/AzurLaneAutoScript, pull requests merged in 2023-12, with the labels that each got.

#3144 Add: Buy the time-limited furniture in dorm.
  assets/cn/dorm/DORM_FURNITURE_BUY_ALL.png
  assets/cn/dorm/DORM_FURNITURE_BUY_CONFIRM.png
  assets/cn/dorm/DORM_FURNITURE_BUY_SET.png
  assets/cn/dorm/DORM_FURNITURE_COUNTDOWN.png
  assets/cn/dorm/DORM_FURNITURE_DETAILS_ENTER.png
  assets/cn/dorm/DORM_FURNITURE_DETAILS_QUIT.png
  assets/cn/dorm/DORM_FURNITURE_SHOP_ENTER.png
  assets/cn/dorm/DORM_FURNITURE_SHOP_FIRST.png
  assets/cn/dorm/DORM_FURNITURE_SHOP_FIRST_SELECTED.png
  assets/cn/dorm/DORM_FURNITURE_SHOP_QUIT.png
  assets/cn/dorm/OCR_DORM_FURNITURE_COIN.png
  assets/cn/dorm/OCR_DORM_FURNITURE_PRICE.png
  assets/en/dorm/DORM_FURNITURE_BUY_ALL.png
  assets/en/dorm/DORM_FURNITURE_BUY_CONFIRM.png
  assets/en/dorm/DORM_FURNITURE_BUY_SET.png
  assets/en/dorm/DORM_FURNITURE_COUNTDOWN.png
  assets/en/dorm/DORM_FURNITURE_DETAILS_ENTER.png
  assets/en/dorm/DORM_FURNITURE_DETAILS_QUIT.png
  assets/en/dorm/DORM_FURNITURE_SHOP_ENTER.png
  assets/en/dorm/DORM_FURNITURE_SHOP_FIRST.png
  assets/en/dorm/DORM_FURNITURE_SHOP_FIRST_SELECTED.png
  assets/en/dorm/DORM_FURNITURE_SHOP_QUIT.png
  assets/en/dorm/OCR_DORM_FURNITURE_COIN.png
  assets/en/dorm/OCR_DORM_FURNITURE_PRICE.png
  assets/jp/dorm/DORM_FURNITURE_BUY_ALL.png
  assets/jp/dorm/DORM_FURNITURE_BUY_CONFIRM.png
  assets/jp/dorm/DORM_FURNITURE_BUY_SET.png
  assets/jp/dorm/DORM_FURNITURE_COUNTDOWN.png
  assets/jp/dorm/DORM_FURNITURE_DETAILS_ENTER.png
  assets/jp/dorm/DORM_FURNITURE_DETAILS_QUIT.png
  assets/jp/dorm/DORM_FURNITURE_SHOP_ENTER.png
  assets/jp/dorm/DORM_FURNITURE_SHOP_FIRST.png
  assets/jp/dorm/DORM_FURNITURE_SHOP_FIRST_SELECTED.png
  assets/jp/dorm/DORM_FURNITURE_SHOP_QUIT.png
  assets/jp/dorm/OCR_DORM_FURNITURE_COIN.png
  assets/jp/dorm/OCR_DORM_FURNITURE_PRICE.png
  assets/tw/dorm/DORM_FURNITURE_BUY_ALL.png
  assets/tw/dorm/DORM_FURNITURE_BUY_CONFIRM.png
  assets/tw/dorm/DORM_FURNITURE_BUY_SET.png
  assets/tw/dorm/DORM_FURNITURE_COUNTDOWN.png
  assets/tw/dorm/DORM_FURNITURE_DETAILS_ENTER.png
  assets/tw/dorm/DORM_FURNITURE_DETAILS_QUIT.png
  assets/tw/dorm/DORM_FURNITURE_SHOP_ENTER.png
  assets/tw/dorm/DORM_FURNITURE_SHOP_FIRST.png
  assets/tw/dorm/DORM_FURNITURE_SHOP_FIRST_SELECTED.png
  assets/tw/dorm/DORM_FURNITURE_SHOP_QUIT.png
  assets/tw/dorm/OCR_DORM_FURNITURE_COIN.png
  assets/tw/dorm/OCR_DORM_FURNITURE_PRICE.png
  config/template.json
  module/config/argument/args.json
  module/config/argument/argument.yaml
  module/config/argument/task.yaml
  module/config/config_generated.py
  module/config/i18n/en-US.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
  module/dorm/assets.py
  module/dorm/buy_furniture.py
  module/dorm/dorm.py
Labels: good first issue / 首次贡献, feature request / 功能请求

#3384 fix: lock jellyfish version to 0.11.2
  deploy/AidLux/0.92/requirements.txt
  deploy/docker/requirements.txt
  deploy/docker/requirements_generator.py
  deploy/headless/requirements_generator.py
  requirements-in.txt
  requirements.txt
Labels: installation / 安装

#3392 Fix: GUILD DISPATCH
  module/device/control.py
Labels: bug / 缺陷, good first issue / 首次贡献

#3387 Fix: Change Fleet_2's ships instead of fixed Fleet_1 when using 'fleet1_standby_fleet2_all'
  module/campaign/gems_farming.py
Labels: bug / 缺陷
