Repository LmeSzinc/AzurLaneAutoScript, pull requests merged in 2023-09, with the labels that each got.

#3078 Fix: OS shop in Akashi
  module/os_handler/shop.py
Labels: bug / 缺陷

#3096 Fix: Error caused by loop of Daily Emergency Module Development
  module/daily/daily.py
Labels: bug / 缺陷

#3098 Update ja-JP.json
  webapp/packages/renderer/src/locales/lang/ja-JP.json
Labels: optimization / 优化

#3097 Fix(JP): Asset of SHOP_BUY_CONFIRM
  assets/jp/os_handler/SHOP_BUY_CONFIRM.gif
  assets/jp/os_handler/SHOP_BUY_CONFIRM.png
  module/os_handler/assets.py
Labels: assets issue / 资源适配问题, Server: JP / 日服

#3103 Fix: End condition order in auto_search_combat of os_combat
  module/os_combat/combat.py
Labels: bug / 缺陷

#3107 add: Migrate to a new image hosting service.
  module/statistics/azurstats.py
Labels: optimization / 优化, good first issue / 首次贡献

#3147 Fix[TW]: Akashi shop buttom grid
  module/os_handler/shop.py
Labels: assets issue / 资源适配问题, Server: TW / 台服

#2996 Add: Dossier Meta Reward Receive
  assets/cn/meta_reward/DOSSIER_REWARD_CHECK.png
  assets/cn/meta_reward/DOSSIER_REWARD_ENTER.png
  assets/cn/meta_reward/DOSSIER_REWARD_RECEIVE.BUTTON.png
  assets/cn/meta_reward/DOSSIER_REWARD_RECEIVE.png
  assets/cn/template/TEMPLATE_META_DOCK_RED_DOT.png
  assets/en/meta_reward/DOSSIER_REWARD_CHECK.png
  assets/en/meta_reward/DOSSIER_REWARD_ENTER.png
  assets/en/meta_reward/DOSSIER_REWARD_RECEIVE.BUTTON.png
  assets/en/meta_reward/DOSSIER_REWARD_RECEIVE.png
  assets/en/template/TEMPLATE_META_DOCK_RED_DOT.png
  assets/jp/meta_reward/DOSSIER_REWARD_CHECK.png
  assets/jp/meta_reward/DOSSIER_REWARD_ENTER.png
  assets/jp/meta_reward/DOSSIER_REWARD_RECEIVE.BUTTON.png
  assets/jp/meta_reward/DOSSIER_REWARD_RECEIVE.png
  assets/jp/template/TEMPLATE_META_DOCK_RED_DOT.png
  assets/tw/template/TEMPLATE_META_DOCK_RED_DOT.png
  module/meta_reward/assets.py
  module/meta_reward/meta_reward.py
  module/os_ash/meta.py
  module/template/assets.py
Labels: feature request / 功能请求

#2881 Upd: Screenshot method DroidCast_raw update
  bin/DroidCast/DroidCast-debug-1.1.0.apk
  bin/DroidCast/DroidCastS-release-1.1.5.apk
  bin/DroidCast/DroidCast_raw-release-1.0.apk
  module/config/config_manual.py
  module/device/method/droidcast.py
Labels: optimization / 优化, good first issue / 首次贡献
