Repository LmeSzinc/AzurLaneAutoScript, pull requests merged in 2023-06, with the labels that each got.

#2731 Upd: [JP] Shop swipe ends
  assets/jp/shop/SHOP_GIFT_SWIPE_END.png
  assets/jp/shop/SHOP_PROTOTYPE_SWIPE_END.png
  module/shop/assets.py
Labels: assets issue / 资源适配问题, Server: JP / 日服

#2579 Add: Allow auto attack dossier
  assets/cn/os_ash/META_AUTO_ATTACK_CONFIRM.png
  assets/cn/os_ash/META_AUTO_ATTACK_START.png
  config/template.json
  module/config/argument/args.json
  module/config/argument/argument.yaml
  module/config/config_generated.py
  module/config/i18n/en-US.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
  module/os_ash/assets.py
  module/os_ash/meta.py
Labels: feature request / 功能请求

#2740 Bug fix: Guild shop PR SELECT
  assets/cn/shop/SHOP_SELECT_PR1.png
  assets/cn/shop/SHOP_SELECT_PR2.png
  assets/cn/shop/SHOP_SELECT_PR3.png
  assets/en/shop/SHOP_SELECT_PR1.png
  assets/en/shop/SHOP_SELECT_PR2.png
  assets/en/shop/SHOP_SELECT_PR3.png
  assets/jp/shop/SHOP_SELECT_PR1.png
  assets/jp/shop/SHOP_SELECT_PR2.png
  assets/jp/shop/SHOP_SELECT_PR3.png
  assets/tw/shop/SHOP_SELECT_PR1.png
  assets/tw/shop/SHOP_SELECT_PR2.png
  assets/tw/shop/SHOP_SELECT_PR3.png
  module/shop/assets.py
Labels: good first issue / 首次贡献, assets issue / 资源适配问题

#2750 Upd: [JP] DOCK_SELECTED
  assets/jp/retire/DOCK_SELECTED.png
  module/retire/assets.py
Labels: assets issue / 资源适配问题, Server: JP / 日服

#2556 Add: Submodule AlasFpyBridge (experimental)
  assets/gui/css/alas.css
  config/template.fpy.json
  module/config/config_updater.py
  module/config/utils.py
  module/submodule/submodule.py
  module/submodule/utils.py
  module/webui/app.py
  module/webui/lang.py
  module/webui/process_manager.py
  submodule/AlasFpyBridge/fpy.py
  submodule/AlasFpyBridge/module/FGOpy.py
  submodule/AlasFpyBridge/module/config/argument/args.json
  submodule/AlasFpyBridge/module/config/argument/argument.yaml
  submodule/AlasFpyBridge/module/config/argument/default.yaml
  submodule/AlasFpyBridge/module/config/argument/menu.json
  submodule/AlasFpyBridge/module/config/argument/override.yaml
  submodule/AlasFpyBridge/module/config/argument/task.yaml
  submodule/AlasFpyBridge/module/config/config.py
  submodule/AlasFpyBridge/module/config/config_generated.py
  submodule/AlasFpyBridge/module/config/config_updater.py
  submodule/AlasFpyBridge/module/config/i18n/en-US.json
  submodule/AlasFpyBridge/module/config/i18n/ja-JP.json
  submodule/AlasFpyBridge/module/config/i18n/zh-CN.json
  submodule/AlasFpyBridge/module/config/i18n/zh-TW.json
  submodule/AlasFpyBridge/module/utils/headlessCliApplication.py
  submodule/AlasFpyBridge/module/utils/orphanSlayer.py
Labels: feature request / 功能请求

#2759 Fix OCR for supply line disruption
  module/daily/daily.py
Labels: bug / 缺陷

#2758 Fix: tactical selecting ship not reset filter
  module/tactical/tactical_class.py
Labels: bug / 缺陷, good first issue / 首次贡献

#2768 Add: Campaign_12_4 Hard
  campaign/campaign_hard/campaign_12_4.py
  module/campaign/run.py
Labels: bug / 缺陷

#2764 Opt: print loading only once in interrupting_auto_search
  module/os/map.py
Labels: optimization / 优化

#2782 feat: headless environment support
  config/deploy.template-linux-cn.yaml
  config/deploy.template-linux.yaml
  deploy/AidLux/0.92/requirements.txt
  deploy/docker/Dockerfile
  deploy/docker/Dockerfile.cn
  deploy/docker/requirements.txt
  deploy/headless/requirements_generator.py
  dev_tools/requirements_updater.py
  module/config/config_updater.py
  requirements-in.txt
Labels: installation / 安装

#2801 Upd: [TW] Event: Counterattack Within the Fjord Rerun
  campaign/Readme.md
  module/config/argument/args.json
  module/config/i18n/en-US.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
Labels: good first issue / 首次贡献, Server: TW / 台服, game event / 游戏活动

#2816 Fix: Error caused by empty build queue
  assets/cn/gacha/BUILD_QUEUE_EMPTY.png
  assets/en/gacha/BUILD_QUEUE_EMPTY.png
  assets/jp/gacha/BUILD_QUEUE_EMPTY.png
  assets/tw/gacha/BUILD_QUEUE_EMPTY.png
  module/gacha/assets.py
  module/gacha/gacha_reward.py
Labels: bug / 缺陷
