Repository LmeSzinc/AzurLaneAutoScript, pull requests merged in 2023-03, with the labels that each got.

#2306 Opt: Optimized hint of Serial
  deploy/emulator.py
  module/config/i18n/en-US.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
Labels: optimization / 优化

#2295 Fix: TaskBalancer malfunctioning caused by ocr failure
  module/campaign/campaign_event.py
  module/campaign/campaign_status.py
  module/campaign/run.py
  module/combat/auto_search_combat.py
Labels: bug / 缺陷

#2331 Fix lanuch game in no physical keys device
  module/device/method/adb.py
Labels: bug / 缺陷

#2341 Upd: Support MAA v4.12.0 beta
  config/template.maa.json
  submodule/AlasMaaBridge/maa.py
  submodule/AlasMaaBridge/module/asst/asst.py
  submodule/AlasMaaBridge/module/config/argument/args.json
  submodule/AlasMaaBridge/module/config/argument/argument.yaml
  submodule/AlasMaaBridge/module/config/config_generated.py
  submodule/AlasMaaBridge/module/config/i18n/en-US.json
  submodule/AlasMaaBridge/module/config/i18n/ja-JP.json
  submodule/AlasMaaBridge/module/config/i18n/zh-CN.json
  submodule/AlasMaaBridge/module/config/i18n/zh-TW.json
  submodule/AlasMaaBridge/module/handler/handler.py
Labels: bug / 缺陷, feature request / 功能请求, Submodule: MAA / MAA插件

#2345 Fix: Wrong condition in MAA infrast
  submodule/AlasMaaBridge/module/handler/handler.py
Labels: bug / 缺陷, Submodule: MAA / MAA插件

#2327 Add: Disable flagship and vanguard change in GemsFarming
  assets/en/ui/FLEET_CHECK.png
  config/template.json
  module/campaign/gems_farming.py
  module/config/argument/args.json
  module/config/argument/argument.yaml
  module/config/config_generated.py
  module/config/i18n/en-US.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
  module/config/redirect_utils/utils.py
  module/ui/assets.py
Labels: optimization / 优化

#2356 Fix: Wrong threshold in MAA infrast
  submodule/AlasMaaBridge/module/handler/handler.py
Labels: bug / 缺陷, Submodule: MAA / MAA插件

#2386 Upd:[TW] Angel of Iris
  assets/tw/raid/IRIS_OCR_PT.png
  assets/tw/raid/IRIS_OCR_REMAIN_EASY.png
  assets/tw/raid/IRIS_OCR_REMAIN_HARD.png
  assets/tw/raid/IRIS_OCR_REMAIN_NORMAL.png
  assets/tw/raid/IRIS_RAID_EASY.png
  assets/tw/raid/IRIS_RAID_HARD.png
  assets/tw/raid/IRIS_RAID_NORMAL.png
  assets/tw/ui/RAID_CHECK.png
  campaign/Readme.md
  module/config/argument/args.json
  module/config/i18n/en-US.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
  module/raid/assets.py
  module/raid/raid.py
  module/ui/assets.py
Labels: Server: TW / 台服, game event / 游戏活动

#2400 Fix: [JP] Asset problem caused by UI hotfix
  assets/jp/coalition/FLEET_PREPARATION.BUTTON.png
  assets/jp/coalition/FLEET_PREPARATION.png
  assets/jp/coalition/FLEET_SWITCH_MULTI.png
  assets/jp/coalition/FLEET_SWITCH_SINGLE.png
  module/coalition/assets.py
Labels: assets issue / 资源适配问题, Server: JP / 日服

#2399 Fix: emotion_reduce when Coalition_Fleet=='multi'
  module/coalition/combat.py
Labels: bug / 缺陷

#2431 Add: Campaign finish notification via Onepush (#2379)
  module/campaign/run.py
Labels: optimization / 优化
