Repository LmeSzinc/AzurLaneAutoScript, pull requests merged in 2023-02, with the labels that each got.

#2193 UPD: [EN] AUTO_SEARCH_SET_ALL, AUTO_SEARCH_SET_STANDBY
  assets/en/handler/AUTO_SEARCH_SET_ALL.png
  assets/en/handler/AUTO_SEARCH_SET_STANDBY.png
  module/handler/assets.py
Labels: assets issue / 资源适配问题, Server: EN / EN服

#2210 Add: Maa Reclamation Algorithm
  config/template.maa.json
  submodule/AlasMaaBridge/maa.py
  submodule/AlasMaaBridge/module/config/argument/args.json
  submodule/AlasMaaBridge/module/config/argument/menu.json
  submodule/AlasMaaBridge/module/config/argument/task.yaml
  submodule/AlasMaaBridge/module/config/config.py
  submodule/AlasMaaBridge/module/config/i18n/en-US.json
  submodule/AlasMaaBridge/module/config/i18n/ja-JP.json
  submodule/AlasMaaBridge/module/config/i18n/zh-CN.json
  submodule/AlasMaaBridge/module/config/i18n/zh-TW.json
  submodule/AlasMaaBridge/module/handler/handler.py
Labels: feature request / 功能请求, Submodule: MAA / MAA插件

#2220 Add support for Bluestacks 5 Pie64 instances
  campaign/Readme.md
  module/config/argument/args.json
  module/config/i18n/en-US.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
  module/device/connection_attr.py
Labels: good first issue / 首次贡献, emulator issue / 模拟器问题

#2225 Opt: Extremely reduce image size built by Dockerfile (-59%)
  deploy/docker/Dockerfile
  deploy/docker/Dockerfile.cn
Labels: optimization / 优化

#2246 一部テキストを日本語へ翻訳 / 将部分文本翻译为日语 / Translate part of the text into Japanese
  README.md
  README_en.md
  README_jp.md
  module/config/i18n/ja-JP.json
Labels: good first issue / 首次贡献, Server: JP / 日服

#2247 Upd [TW] Abyssal Refrain
  campaign/Readme.md
  module/config/argument/args.json
  module/config/i18n/en-US.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
Labels: Server: TW / 台服, game event / 游戏活动

#2258 Opt: Adjust help message of CL1 leveling
  config/template.json
  module/config/argument/args.json
  module/config/argument/menu.json
  module/config/argument/task.yaml
  module/config/i18n/en-US.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
Labels: optimization / 优化

#2266 Fix: wrong value coding in get_action_point_limit
  module/config/i18n/en-US.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
  module/os/map.py
Labels: bug / 缺陷

#2267 Fix: Replaced "monk battle" to "practice battle"
  module/config/i18n/en-US.json
Labels: bug / 缺陷

#2257 Add: Option to delay buying weekly supply pack
  config/template.json
  module/config/argument/args.json
  module/config/argument/argument.yaml
  module/config/config_generated.py
  module/config/i18n/en-US.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
  module/config/utils.py
  module/freebies/supply_pack.py
Labels: feature request / 功能请求

#2277 Upd: Support of MAA v4.11.0
  config/template.maa.json
  submodule/AlasMaaBridge/module/asst/__init__.py
  submodule/AlasMaaBridge/module/asst/asst.py
  submodule/AlasMaaBridge/module/asst/updater.py
  submodule/AlasMaaBridge/module/asst/utils.py
  submodule/AlasMaaBridge/module/config/argument/args.json
  submodule/AlasMaaBridge/module/config/argument/argument.yaml
  submodule/AlasMaaBridge/module/config/argument/override.yaml
  submodule/AlasMaaBridge/module/config/config_generated.py
  submodule/AlasMaaBridge/module/config/i18n/en-US.json
  submodule/AlasMaaBridge/module/config/i18n/ja-JP.json
  submodule/AlasMaaBridge/module/config/i18n/zh-CN.json
  submodule/AlasMaaBridge/module/config/i18n/zh-TW.json
  submodule/AlasMaaBridge/module/handler/handler.py
Labels: feature request / 功能请求, Submodule: MAA / MAA插件

#2280 Fix: Fix update stuck issue
  deploy/git.py
Labels: bug / 缺陷, good first issue / 首次贡献

#2281 Add: Revelations of Dust chapter AC
  assets/cn/template/TEMPLATE_SIREN_Joffre.gif
  assets/cn/template/TEMPLATE_SIREN_LaGalissonniere.gif
  assets/cn/template/TEMPLATE_SIREN_LeMars.gif
  assets/en/template/TEMPLATE_SIREN_Joffre.gif
  assets/en/template/TEMPLATE_SIREN_LaGalissonniere.gif
  assets/en/template/TEMPLATE_SIREN_LeMars.gif
  assets/jp/template/TEMPLATE_SIREN_Joffre.gif
  assets/jp/template/TEMPLATE_SIREN_LaGalissonniere.gif
  assets/jp/template/TEMPLATE_SIREN_LeMars.gif
  assets/tw/template/TEMPLATE_SIREN_Joffre.gif
  assets/tw/template/TEMPLATE_SIREN_LaGalissonniere.gif
  assets/tw/template/TEMPLATE_SIREN_LeMars.gif
  campaign/Readme.md
  campaign/event_20230223_cn/a1.py
  campaign/event_20230223_cn/a2.py
  campaign/event_20230223_cn/a3.py
  campaign/event_20230223_cn/c1.py
  campaign/event_20230223_cn/c2.py
  campaign/event_20230223_cn/c3.py
  deploy/git.py
  dev_tools/map_extractor.py
  module/config/argument/args.json
  module/config/i18n/en-US.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
  module/template/assets.py
Labels: game event / 游戏活动

#2297 Fix: sync python executable with python 3.7 slim image
  assets/en/dorm/DORM_FURNITURE_CONFIRM.png
  assets/en/os_handler/ACTION_POINT_REMAIN_OS.png
  assets/en/retire/DOCK_AMOUNT.png
  assets/en/retire/RETIRE_SETTING_1.png
  assets/en/retire/RETIRE_SETTING_2.png
  assets/en/retire/RETIRE_SETTING_3.png
  assets/en/retire/RETIRE_SETTING_4.png
  assets/en/retire/RETIRE_SETTING_5_ALL.png
  assets/en/retire/RETIRE_SETTING_5_PRESERVE.png
  assets/en/retire/RETIRE_SETTING_QUIT.png
  assets/en/war_archives/TEMPLATE_CRESCENDO_OF_POLARIS.png
  assets/en/war_archives/TEMPLATE_THE_ENIGMA_AND_THE_SHARK.png
  assets/en/war_archives/TEMPLATE_THE_SOLOMON_RANGER.png
  assets/en/war_archives/TEMPLATE_UNIVERSE_IN_UNISON.png
  module/config/config_updater.py
  module/dorm/assets.py
  module/os_handler/assets.py
  module/retire/assets.py
  module/war_archives/assets.py
Labels: installation / 安装
