Repository LmeSzinc/AzurLaneAutoScript, pull requests merged in 2023-07, with the labels that each got.

#2821 Upd: [EN] assets and allow for gorizia ex auto raid
  assets/cn/raid/GORIZIA_OCR_REMAIN_EX.png
  assets/en/handler/GET_SKIN.png
  assets/en/os_ash/META_AUTO_ATTACK_CONFIRM.png
  assets/en/os_ash/META_AUTO_ATTACK_START.png
  assets/en/raid/GORIZIA_OCR_REMAIN_EX.png
  assets/en/shop/SHOP_GIFT_SWIPE_END.png
  assets/en/template/TEMPLATE_SIREN_SheffieldIdol.png
  assets/en/war_archives/TEMPLATE_AURORA_NOCTIS.png
  assets/en/war_archives/TEMPLATE_MICROLAYER_MEDLEY.png
  assets/en/war_archives/TEMPLATE_NORTHERN_OVERTURE.png
  assets/en/war_archives/TEMPLATE_SKYBOUND_ORATORIO.png
  assets/en/war_archives/TEMPLATE_STARS_OF_THE_SHIMMERING_FJORD.png
  assets/en/war_archives/TEMPLATE_THE_WAY_HOME_IN_THE_NIGHT.png
  assets/jp/raid/GORIZIA_RAID_EASY.png
  assets/jp/raid/GORIZIA_RAID_HARD.png
  assets/jp/raid/GORIZIA_RAID_NORMAL.png
  assets/jp/ui/RAID_CHECK.png
  module/handler/assets.py
  module/os_ash/assets.py
  module/raid/assets.py
  module/raid/raid.py
  module/raid/run.py
  module/shop/assets.py
  module/shop/ui.py
  module/template/assets.py
  module/ui/assets.py
  module/war_archives/assets.py
Labels: assets issue / 资源适配问题

#2829 Fix: add RAID_REWARDS.png to fix raid reward problem
  assets/cn/raid/RAID_REWARDS.png
  assets/en/raid/RAID_REWARDS.png
  assets/jp/raid/RAID_REWARDS.png
  assets/tw/raid/RAID_REWARDS.png
  module/raid/assets.py
  module/raid/raid.py
Labels: bug / 缺陷, good first issue / 首次贡献

#2837 Fix: Retire get stuck if nothing can be retired
  module/retire/retirement.py
Labels: bug / 缺陷

#2841 Fix: Error caused by queue clean status flashback
  module/gacha/gacha_reward.py
Labels: bug / 缺陷

#2872 Add: Blueprint assets of research S6
  assets/research_blueprint/flandre.png
  assets/research_blueprint/hindenburg.png
  assets/research_blueprint/kearsarge.png
  assets/research_blueprint/schultz.png
  assets/research_blueprint/shimanto.png
Labels: assets issue / 资源适配问题, Server: JP / 日服

#2871 Upd: [TW] Event:Operation Convergence
  campaign/Readme.md
  module/config/argument/args.json
  module/config/i18n/en-US.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
Labels: Server: TW / 台服, game event / 游戏活动

#2864 Add: Consume spilled Coins
  config/template.json
  module/config/argument/args.json
  module/config/argument/argument.yaml
  module/config/config_generated.py
  module/config/i18n/en-US.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
  module/shop/shop_general.py
Labels: feature request / 功能请求

#2912 Upd: World-spanning Arclight Rerun chapter TSS
  campaign/event_20211125_cn/tss1.py
  campaign/event_20211125_cn/tss2.py
  campaign/event_20211125_cn/tss3.py
  campaign/event_20211125_cn/tss4.py
  campaign/event_20211125_cn/tss5.py
  module/campaign/campaign_ui.py
Labels: game event / 游戏活动

#2938 Upd:[TW] Event:Dreamwaker's Butterfly Rerun
  campaign/Readme.md
  module/config/argument/args.json
  module/config/i18n/en-US.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
Labels: Server: TW / 台服, game event / 游戏活动
