Repository LmeSzinc/AzurLaneAutoScript, pull requests merged in 2023-01, with the labels that each got.

#2060 Fix: Unable to stop MAA when error occurred
  submodule/AlasMaaBridge/maa.py
  submodule/AlasMaaBridge/module/handler/handler.py
Labels: bug / 缺陷, Submodule: MAA / MAA插件

#2098 Fix: Overconsumption of AP by meowfficer farming
  module/os/operation_siren.py
  module/os_handler/action_point.py
Labels: bug / 缺陷

#2112 EN Bug fix + Others
  assets/en/exercise/QUIT_CONFIRM.png
  assets/en/exercise/QUIT_RECONFIRM.png
  module/exercise/assets.py
  module/os/globe_operation.py
  module/os/map.py
  module/os/operation_siren.py
  module/os_handler/enemy_searching.py
Labels: bug / 缺陷, assets issue / 资源适配问题, Server: EN / EN服

#2127 Fix: Missing timer reset in MAA callback
  submodule/AlasMaaBridge/module/config/i18n/zh-CN.json
  submodule/AlasMaaBridge/module/handler/handler.py
Labels: bug / 缺陷

#2124 Add: Start app by adb shell am start
  module/device/method/adb.py
Labels: feature request / 功能请求

#2120 Fix: Keep 1000 AP only when CL1 available but not enabled
  module/config/config_manual.py
  module/os/map.py
  module/os/operation_siren.py
Labels: bug / 缺陷

#2134 Fix: Unable to install minitouch in MuMu X
  deploy/adb.py
  module/device/connection.py
Labels: bug / 缺陷

#2135 Fix: Wrongly identify mod when auto-run config
  module/webui/process_manager.py
Labels: bug / 缺陷

#2167 Add: SSSCopilot Support of MAA
  config/template.maa.json
  submodule/AlasMaaBridge/maa.py
  submodule/AlasMaaBridge/module/config/argument/args.json
  submodule/AlasMaaBridge/module/config/argument/argument.yaml
  submodule/AlasMaaBridge/module/config/config_generated.py
  submodule/AlasMaaBridge/module/config/i18n/en-US.json
  submodule/AlasMaaBridge/module/config/i18n/ja-JP.json
  submodule/AlasMaaBridge/module/config/i18n/zh-CN.json
  submodule/AlasMaaBridge/module/config/i18n/zh-TW.json
  submodule/AlasMaaBridge/module/handler/handler.py
Labels: feature request / 功能请求

#2166 Fix: Typo error in MAA interface
  submodule/AlasMaaBridge/module/handler/handler.py
Labels: bug / 缺陷

#2162 Fix: Clicking on equipment 'disassemble' button too fast
  module/storage/ui.py
Labels: bug / 缺陷, good first issue / 首次贡献

#2173 Opt: Add optional MAA installation for Docker
  deploy/docker/Docker-run.sh
  deploy/docker/Dockerfile
  deploy/docker/Dockerfile.cn
  docker-compose.yml
Labels: good first issue / 首次贡献, installation / 安装

#2182 Fix: Install missing dependencies for new docker image
  deploy/docker/Dockerfile
  deploy/docker/Dockerfile.cn
Labels: bug / 缺陷, installation / 安装

#2096 Add: Auto disable event task when no event (#1396)
  assets/cn/ui/CAMPAIGN_MENU_NO_EVENT.png
  assets/en/ui/CAMPAIGN_MENU_NO_EVENT.png
  assets/jp/ui/CAMPAIGN_MENU_NO_EVENT.png
  module/campaign/campaign_event.py
  module/ui/assets.py
Labels: optimization / 优化
