Repository LmeSzinc/AzurLaneAutoScript, pull requests merged in 2024-04, with the labels that each got.

#3598 Upd: Assets FORMATION to adapt to W15
  assets/cn/handler/FORMATION_1.BUTTON.png
  assets/cn/handler/FORMATION_1.png
  assets/cn/handler/FORMATION_2.BUTTON.png
  assets/cn/handler/FORMATION_2.png
  assets/cn/handler/FORMATION_3.BUTTON.png
  assets/cn/handler/FORMATION_3.png
  assets/en/handler/FORMATION_1.BUTTON.png
  assets/en/handler/FORMATION_1.png
  assets/en/handler/FORMATION_2.BUTTON.png
  assets/en/handler/FORMATION_2.png
  assets/en/handler/FORMATION_3.BUTTON.png
  assets/en/handler/FORMATION_3.png
  assets/jp/handler/FORMATION_1.BUTTON.png
  assets/jp/handler/FORMATION_1.png
  assets/jp/handler/FORMATION_2.BUTTON.png
  assets/jp/handler/FORMATION_2.png
  assets/jp/handler/FORMATION_3.BUTTON.png
  assets/jp/handler/FORMATION_3.png
  assets/tw/handler/FORMATION_1.BUTTON.png
  assets/tw/handler/FORMATION_1.png
  assets/tw/handler/FORMATION_2.BUTTON.png
  assets/tw/handler/FORMATION_2.png
  assets/tw/handler/FORMATION_3.BUTTON.png
  assets/tw/handler/FORMATION_3.png
  module/handler/assets.py
Labels: assets issue / 资源适配问题

#3608 Fix: Reset dock sorting after changing ship
  module/campaign/gems_farming.py
Labels: bug / 缺陷

#3612 Opt: load offsets of auto search settings at fleet preparation stage
  module/handler/auto_search.py
  module/map/map_fleet_preparation.py
Labels: bug / 缺陷

#3618 fix: ship template assets bit error
  assets/cn/retire/TEMPLATE_AULICK.png
  assets/cn/retire/TEMPLATE_BOGUE.png
  assets/cn/retire/TEMPLATE_CASSIN_1.png
  assets/cn/retire/TEMPLATE_CASSIN_2.png
  assets/cn/retire/TEMPLATE_DOWNES_1.png
  assets/cn/retire/TEMPLATE_DOWNES_2.png
  assets/cn/retire/TEMPLATE_FOOTE.png
  assets/cn/retire/TEMPLATE_HERMES.png
  assets/cn/retire/TEMPLATE_LANGLEY.png
  assets/cn/retire/TEMPLATE_RANGER.png
  assets/en/retire/TEMPLATE_AULICK.png
  assets/en/retire/TEMPLATE_BOGUE.png
  assets/en/retire/TEMPLATE_CASSIN_1.png
  assets/en/retire/TEMPLATE_CASSIN_2.png
  assets/en/retire/TEMPLATE_DOWNES_1.png
  assets/en/retire/TEMPLATE_DOWNES_2.png
  assets/en/retire/TEMPLATE_FOOTE.png
  assets/en/retire/TEMPLATE_HERMES.png
  assets/en/retire/TEMPLATE_LANGLEY.png
  assets/en/retire/TEMPLATE_RANGER.png
  assets/jp/retire/TEMPLATE_AULICK.png
  assets/jp/retire/TEMPLATE_BOGUE.png
  assets/jp/retire/TEMPLATE_CASSIN_1.png
  assets/jp/retire/TEMPLATE_CASSIN_2.png
  assets/jp/retire/TEMPLATE_DOWNES_1.png
  assets/jp/retire/TEMPLATE_DOWNES_2.png
  assets/jp/retire/TEMPLATE_FOOTE.png
  assets/jp/retire/TEMPLATE_HERMES.png
  assets/jp/retire/TEMPLATE_LANGLEY.png
  assets/jp/retire/TEMPLATE_RANGER.png
  assets/tw/retire/TEMPLATE_AULICK.png
  assets/tw/retire/TEMPLATE_BOGUE.png
  assets/tw/retire/TEMPLATE_CASSIN_1.png
  assets/tw/retire/TEMPLATE_CASSIN_2.png
  assets/tw/retire/TEMPLATE_DOWNES_1.png
  assets/tw/retire/TEMPLATE_DOWNES_2.png
  assets/tw/retire/TEMPLATE_FOOTE.png
  assets/tw/retire/TEMPLATE_HERMES.png
  assets/tw/retire/TEMPLATE_LANGLEY.png
  assets/tw/retire/TEMPLATE_RANGER.png
  module/retire/assets.py
Labels: assets issue / 资源适配问题

#3622 Add: HOMO_STORAGE data for d2/d4 in Divergent Chessboard
  campaign/war_archives_20191031_en/b2.py
  campaign/war_archives_20191031_en/b4.py
  campaign/war_archives_20191031_en/d2.py
  campaign/war_archives_20191031_en/d4.py
Labels: bug / 缺陷

#3629 Add: Event entrance of Abyssal Refrain Rerun
  campaign/Readme.md
  module/config/argument/args.json
  module/config/i18n/en-US.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
Labels: game event / 游戏活动

#3637 Add: Medal Shop item SpecializedCore
  assets/shop/medal/SpecializedCore.png
  module/shop/base.py
Labels: assets issue / 资源适配问题

#3648 Fix: fall back to all union DDs when not specifying DD
  module/campaign/gems_farming.py
Labels: bug / 缺陷

#3653 Opt: sort latest events in config update
  module/config/config_updater.py
Labels: optimization / 优化

#3643 Upgrade onepush
  deploy/AidLux/0.92/requirements.txt
  deploy/docker/requirements.txt
  requirements-in.txt
  requirements.txt
Labels: installation / 安装

#3563 Add: 15图开荒/周回
  assets/cn/handler/MOB_MOVE_1.png
  assets/cn/handler/MOB_MOVE_2.png
  assets/cn/handler/MOB_MOVE_CANCEL.png
  assets/cn/template/TEMPLATE_ENEMY_CarrierSpecial.gif
  assets/cn/template/TEMPLATE_MOB_MOVE_ICON.png
  assets/en/handler/MOB_MOVE_1.png
  assets/en/handler/MOB_MOVE_2.png
  assets/jp/handler/MOB_MOVE_1.png
  assets/jp/handler/MOB_MOVE_2.png
  assets/jp/handler/MOB_MOVE_CANCEL.png
  assets/mask/MASK_MAP_UI_W15.png
  assets/tw/handler/MOB_MOVE_1.png
  assets/tw/handler/MOB_MOVE_2.png
  campaign/campaign_main/campaign_15_1.py
  campaign/campaign_main/campaign_15_2.py
  campaign/campaign_main/campaign_15_3.py
  campaign/campaign_main/campaign_15_4.py
  campaign/campaign_main/campaign_15_base.py
  module/handler/assets.py
  module/handler/strategy.py
  module/map/camera.py
  module/map_detection/grid_predictor.py
  module/template/assets.py
Labels: feature request / 功能请求

#3556 Upd: Flagship changing
  assets/cn/equipment/EQUIP_1.png
  assets/cn/equipment/EQUIP_2.png
  assets/cn/equipment/EQUIP_3.png
  assets/cn/equipment/FLEET_DETAIL.png
  assets/cn/equipment/FLEET_DETAIL_CHECK.png
  assets/cn/equipment/FLEET_DETAIL_ENTER.png
  assets/cn/equipment/FLEET_DETAIL_ENTER_FLAGSHIP.png
  assets/cn/equipment/FLEET_ENTER_FLAGSHIP.png
  assets/cn/exercise/EQUIP_ENTER.png
  assets/en/equipment/FLEET_DETAIL.png
  assets/en/equipment/FLEET_DETAIL_CHECK.png
  assets/en/equipment/FLEET_DETAIL_ENTER.png
  assets/en/equipment/FLEET_DETAIL_ENTER_FLAGSHIP.png
  assets/en/equipment/FLEET_ENTER_FLAGSHIP.png
  assets/en/exercise/EQUIP_ENTER.png
  assets/jp/equipment/FLEET_DETAIL.png
  assets/jp/equipment/FLEET_DETAIL_CHECK.png
  assets/jp/equipment/FLEET_DETAIL_ENTER.png
  assets/jp/equipment/FLEET_DETAIL_ENTER_FLAGSHIP.png
  assets/jp/equipment/FLEET_ENTER_FLAGSHIP.png
  assets/jp/exercise/EQUIP_ENTER.png
  assets/tw/equipment/FLEET_DETAIL.png
  assets/tw/equipment/FLEET_DETAIL_CHECK.png
  assets/tw/equipment/FLEET_DETAIL_ENTER.png
  assets/tw/equipment/FLEET_DETAIL_ENTER_FLAGSHIP.png
  assets/tw/equipment/FLEET_ENTER_FLAGSHIP.png
  assets/tw/exercise/EQUIP_ENTER.png
  module/campaign/gems_farming.py
  module/daily/daily.py
  module/daily/equipment.py
  module/equipment/assets.py
  module/equipment/equipment.py
  module/equipment/equipment_change.py
  module/equipment/fleet_equipment.py
  module/exercise/assets.py
  module/exercise/combat.py
  module/exercise/equipment.py
  module/hard/equipment.py
  module/retire/dock.py
Labels: optimization / 优化

#3655 Fix: force battle function choice for 15-3/15-4 when clear all
  campaign/campaign_main/campaign_15_3.py
  campaign/campaign_main/campaign_15_4.py
Labels: bug / 缺陷

#3659 Opt: INTERNAL_LINES_FIND_PEAKS_PARAMETERS for W15
  campaign/campaign_main/campaign_15_base.py
Labels: bug / 缺陷

#3665 Fix: rename equipment functions
  module/retire/enhancement.py
Labels: bug / 缺陷

#3674 Upd: asset FLEET_DETAIL_CHECK
  assets/cn/equipment/FLEET_DETAIL_CHECK.png
  assets/en/equipment/FLEET_DETAIL_CHECK.png
  assets/jp/equipment/FLEET_DETAIL_CHECK.png
  assets/tw/equipment/FLEET_DETAIL_CHECK.png
  module/equipment/assets.py
Labels: assets issue / 资源适配问题

#3675 Opt: sort asset lines before printing to file
  dev_tools/button_extract.py
  module/template/assets.py
Labels: optimization / 优化

#3677 Upd:[TW]Event:The Fool's Scales
  campaign/Readme.md
  module/config/argument/args.json
  module/config/i18n/zh-TW.json
Labels: Server: TW / 台服, game event / 游戏活动

#3681 Add: jp event entrance 20240425
  campaign/Readme.md
  module/config/argument/args.json
  module/config/i18n/ja-JP.json
Labels: Server: JP / 日服, game event / 游戏活动

#3700 Fix: equipment image record in fast PC
  module/equipment/equipment_change.py
Labels: bug / 缺陷
