Repository LmeSzinc/AzurLaneAutoScript, pull requests merged in 2024-07, with the labels that each got.

#3947 Fix: none cost
  assets/shop/os/EmptyT1_1.png
  assets/shop/os/EmptyT2_1.png
  module/os_shop/item.py
  module/os_shop/port_shop.py
  module/os_shop/shop.py
Labels: bug / 缺陷

#3837 Add: Quick collection of coins and loves in the Dorm.
  assets/cn/dorm/DORM_QUICK_COLLECT.png
  assets/en/dorm/DORM_QUICK_COLLECT.png
  assets/jp/dorm/DORM_QUICK_COLLECT.png
  assets/tw/dorm/DORM_QUICK_COLLECT.png
  module/dorm/assets.py
  module/dorm/dorm.py
Labels: feature request / 功能请求

#3987 Fix BlueStacks_nxt emulator auto-run
  module/device/platform/platform_windows.py
Labels: bug / 缺陷, good first issue / 首次贡献
