Repository LmeSzinc/AzurLaneAutoScript, pull requests merged in 2024-01, with the labels that each got.

#3419 Chore: ignore Pylance config file
  .gitignore
Labels: documentation / 文档

#3460 Add: Add raid event Spring Festive Fiasco(raid_20240130)
  assets/cn/raid/HUANCHANG_OCR_PT.png
  assets/cn/raid/HUANCHANG_OCR_REMAIN_EASY.png
  assets/cn/raid/HUANCHANG_OCR_REMAIN_EX.png
  assets/cn/raid/HUANCHANG_OCR_REMAIN_HARD.png
  assets/cn/raid/HUANCHANG_OCR_REMAIN_NORMAL.png
  assets/cn/raid/HUANCHANG_RAID_EASY.png
  assets/cn/raid/HUANCHANG_RAID_EX.png
  assets/cn/raid/HUANCHANG_RAID_HARD.png
  assets/cn/raid/HUANCHANG_RAID_NORMAL.png
  assets/cn/ui/RAID_CHECK.png
  assets/en/raid/HUANCHANG_OCR_PT.png
  assets/en/raid/HUANCHANG_OCR_REMAIN_EASY.png
  assets/en/raid/HUANCHANG_OCR_REMAIN_EX.png
  assets/en/raid/HUANCHANG_OCR_REMAIN_HARD.png
  assets/en/raid/HUANCHANG_OCR_REMAIN_NORMAL.png
  assets/en/raid/HUANCHANG_RAID_EASY.png
  assets/en/raid/HUANCHANG_RAID_EX.png
  assets/en/raid/HUANCHANG_RAID_HARD.png
  assets/en/raid/HUANCHANG_RAID_NORMAL.png
  assets/en/ui/RAID_CHECK.png
  assets/jp/raid/HUANCHANG_OCR_PT.png
  assets/jp/raid/HUANCHANG_OCR_REMAIN_EASY.png
  assets/jp/raid/HUANCHANG_OCR_REMAIN_EX.png
  assets/jp/raid/HUANCHANG_OCR_REMAIN_HARD.png
  assets/jp/raid/HUANCHANG_OCR_REMAIN_NORMAL.png
  assets/jp/raid/HUANCHANG_RAID_EASY.png
  assets/jp/raid/HUANCHANG_RAID_EX.png
  assets/jp/raid/HUANCHANG_RAID_HARD.png
  assets/jp/raid/HUANCHANG_RAID_NORMAL.png
  assets/jp/ui/RAID_CHECK.png
  campaign/Readme.md
  module/config/argument/args.json
  module/config/i18n/en-US.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/raid/assets.py
  module/raid/raid.py
  module/ui/assets.py
Labels: game event / 游戏活动

#3464 Upd: Update raid_20240130 assets for CN sever.
  assets/cn/raid/HUANCHANG_OCR_REMAIN_EASY.png
  assets/cn/raid/HUANCHANG_OCR_REMAIN_HARD.png
  assets/cn/raid/HUANCHANG_OCR_REMAIN_NORMAL.png
  assets/cn/raid/HUANCHANG_RAID_EASY.png
  assets/cn/raid/HUANCHANG_RAID_EX.png
  assets/cn/raid/HUANCHANG_RAID_HARD.png
  assets/cn/raid/HUANCHANG_RAID_NORMAL.png
  module/raid/assets.py
Labels: assets issue / 资源适配问题, Server: CN / 国服

#3462 Upd: Shipyard argument (PR4 and DR3)
  module/config/argument/args.json
  module/config/argument/argument.yaml
  module/config/config_generated.py
  module/config/i18n/en-US.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
Labels: game event / 游戏活动
