Repository LmeSzinc/AzurLaneAutoScript, pull requests merged in 2024-05, with the labels that each got.

#3714 Upd: Support MAA v5.2.3-alpha.1.d011.g704145a3d
  config/template.maa.json
  submodule/AlasMaaBridge/module/config/argument/args.json
  submodule/AlasMaaBridge/module/config/argument/argument.yaml
  submodule/AlasMaaBridge/module/config/argument/task.yaml
  submodule/AlasMaaBridge/module/config/config_generated.py
  submodule/AlasMaaBridge/module/config/config_updater.py
  submodule/AlasMaaBridge/module/config/i18n/en-US.json
  submodule/AlasMaaBridge/module/config/i18n/ja-JP.json
  submodule/AlasMaaBridge/module/config/i18n/zh-CN.json
  submodule/AlasMaaBridge/module/config/i18n/zh-TW.json
  submodule/AlasMaaBridge/module/handler/handler.py
Labels: good first issue / 首次贡献, feature request / 功能请求, Submodule: MAA / MAA插件

#3735 Upd: gui text
  config/template.json
  module/config/argument/args.json
  module/config/argument/argument.yaml
  module/config/config_generated.py
  module/config/i18n/en-US.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
Labels: documentation / 文档

#3736 Upd: MAA Fight&Recruit
  config/template.maa.json
  submodule/AlasMaaBridge/module/config/argument/args.json
  submodule/AlasMaaBridge/module/config/argument/argument.yaml
  submodule/AlasMaaBridge/module/config/config_generated.py
  submodule/AlasMaaBridge/module/config/i18n/en-US.json
  submodule/AlasMaaBridge/module/config/i18n/ja-JP.json
  submodule/AlasMaaBridge/module/config/i18n/zh-CN.json
  submodule/AlasMaaBridge/module/config/i18n/zh-TW.json
  submodule/AlasMaaBridge/module/handler/handler.py
Labels: feature request / 功能请求, Submodule: MAA / MAA插件

#3746 Feat/updatereadme
  README.md
  README_en.md
  README_jp.md
Labels: documentation / 文档, good first issue / 首次贡献

#3783 Fix: avoid continuous clicking AUTO_SEARCH_OS_MAP_OPTION_OFF
  module/os_handler/map_event.py
Labels: bug / 缺陷
