Repository LmeSzinc/AzurLaneAutoScript, pull requests merged in 2024-06, with the labels that each got.

#3751 Fix: increase tile_center matching success rate in light map
  campaign/campaign_main/campaign_12_1.py
  campaign/campaign_main/campaign_13_1.py
  campaign/campaign_main/campaign_15_base.py
  campaign/campaign_main/campaign_1_1.py
  campaign/campaign_main/campaign_2_1.py
  campaign/campaign_main/campaign_3_1.py
  campaign/campaign_main/campaign_5_1.py
Labels: bug / 缺陷

#3764 Fix: mob move optimization
  assets/cn/handler/MOB_MOVE_1.png
  assets/cn/handler/MOB_MOVE_2.png
  assets/cn/handler/MOB_MOVE_ENTER.png
  assets/en/handler/MOB_MOVE_1.png
  assets/en/handler/MOB_MOVE_2.png
  assets/en/handler/MOB_MOVE_ENTER.png
  assets/jp/handler/MOB_MOVE_1.png
  assets/jp/handler/MOB_MOVE_2.png
  assets/jp/handler/MOB_MOVE_ENTER.png
  assets/tw/handler/MOB_MOVE_1.png
  assets/tw/handler/MOB_MOVE_2.png
  assets/tw/handler/MOB_MOVE_ENTER.png
  campaign/campaign_main/campaign_15_2.py
  campaign/campaign_main/campaign_15_base.py
  module/handler/assets.py
  module/handler/strategy.py
Labels: bug / 缺陷

#3832 Opt: wait until navbar active is not None
  module/gacha/ui.py
  module/ui/navbar.py
Labels: bug / 缺陷

#3860 Fix: RewardShipyard ocr coin in page_reshmenu
  module/shipyard/shipyard_reward.py
Labels: bug / 缺陷

#3880 fix exception when tactical book is empty
  module/tactical/tactical_class.py
Labels: bug / 缺陷

#3886 Upd:[TW]Event:Sundered Blue Rerun
  campaign/Readme.md
  module/config/argument/args.json
  module/config/i18n/zh-TW.json
Labels: Server: TW / 台服, game event / 游戏活动

#3885 Fix: use ui_ensure to handle FATE(Unknown ui page)
  module/shipyard/shipyard_reward.py
Labels: bug / 缺陷

#3786 Upd: add CommonDD option
  module/campaign/gems_farming.py
  module/config/argument/args.json
  module/config/argument/argument.yaml
  module/config/config_generated.py
  module/config/i18n/en-US.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
Labels: optimization / 优化

#3902 Add: Event Rondo at Rainbow's End Rerun
  campaign/Readme.md
  module/config/argument/args.json
  module/config/i18n/en-US.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
Labels: game event / 游戏活动

#3925 Fix: update camera_data of a/c2 in event_20220428_cn
  campaign/event_20220428_cn/a2.py
  campaign/event_20220428_cn/c2.py
Labels: bug / 缺陷

#3867 Opt: Add start/stop LDPlayer,NoxPlayer,BlueStack4,MEmuPlayer support.
  module/device/platform/emulator_base.py
  module/device/platform/emulator_windows.py
  module/device/platform/platform_windows.py
Labels: emulator issue / 模拟器问题

#3930 fix: handle sidebar disappear
  module/config/i18n/en-US.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
  module/os/operation_siren.py
  module/os_handler/port.py
  module/os_shop/ui.py
Labels: bug / 缺陷

#3938 fix: add mxnet-alas for linux
  deploy/docker/requirements.txt
  deploy/docker/requirements_generator.py
  deploy/headless/requirements.txt
  deploy/headless/requirements_generator.py
Labels: installation / 安装
