Repository LmeSzinc/AzurLaneAutoScript, pull requests merged in 2025-02, with the labels that each got.

#4548 Fix: guild operations should start based on server time instead of local time
  module/config/utils.py
  module/guild/operations.py
Labels: bug / 缺陷

#4554 Upd: [JP] ash_collect_status
  assets/jp/os_ash/ASH_DAILY_STATUS.png
  module/os_ash/ash.py
  module/os_ash/assets.py
Labels: bug / 缺陷, Server: JP / 日服

#4570 Fix: Incorrect truncation of slider bar
  module/os_shop/port_shop.py
  module/os_shop/ui.py
Labels: bug / 缺陷

#4595 Fix: Installations in containers have no access to remote access
  deploy/docker/Dockerfile
  deploy/docker/Dockerfile.cn
Labels: good first issue / 首次贡献, installation / 安装

#4529 更新onepush版本，以修复gotify无法正常推送的问题
  deploy/AidLux/0.92/requirements.txt
  deploy/docker/requirements.txt
  deploy/headless/requirements.txt
  requirements-in.txt
  requirements.txt
Labels: bug / 缺陷

#4600 Upd: OCR parameters for JP zone name recognition
  module/os/map_operation.py
Labels: bug / 缺陷, Server: JP / 日服

#4601 Upd: [JP] PRICE_OCR in os_shop
  module/os_shop/item.py
Labels: bug / 缺陷, Server: JP / 日服
