Repository LmeSzinc/AzurLaneAutoScript, pull requests merged in 2025-03, with the labels that each got.

#4629 Revert commit ca0f483 for en only
  assets/en/guild/OCR_GUILD_OPERATIONS_PROGRESS.png
  module/guild/assets.py
Labels: assets issue / 资源适配问题, Server: EN / EN服

#4645 Fix: [FPY] 我要保证我见到lme的时候AlasFpyBridge是可用的!
  submodule/AlasFpyBridge/fpy.py
  submodule/AlasFpyBridge/module/FGOpy.py
  submodule/AlasFpyBridge/module/config/argument/args.json
  submodule/AlasFpyBridge/module/config/argument/argument.yaml
  submodule/AlasFpyBridge/module/config/i18n/en-US.json
  submodule/AlasFpyBridge/module/config/i18n/ja-JP.json
  submodule/AlasFpyBridge/module/config/i18n/zh-CN.json
  submodule/AlasFpyBridge/module/utils/headlessCliApplication.py
Labels: bug / 缺陷

#4636 Fix: vanguard_change logic
  module/campaign/gems_farming.py
  module/retire/scanner.py
Labels: optimization / 优化

#4662 Upd: Submarine EN assets
  assets/en/handler/SUBMARINE_MOVE_CANCEL.png
  assets/en/handler/SUBMARINE_MOVE_CONFIRM.png
  module/handler/assets.py
Labels: assets issue / 资源适配问题, Server: EN / EN服

#4684 Upd: ocr params for get_zone_name in JP server
  module/os/map_operation.py
Labels: bug / 缺陷, Server: JP / 日服

#4698 Add: War Archives 20220324
  assets/cn/war_archives/TEMPLATE_VIRTUAL_TOWER.png
  campaign/Readme.md
  campaign/war_archives_20220324_cn/sp1.py
  campaign/war_archives_20220324_cn/sp2.py
  campaign/war_archives_20220324_cn/sp3.py
  campaign/war_archives_20220324_cn/sp4.py
  config/template.json
  module/config/argument/args.json
  module/config/i18n/en-US.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
  module/config/i18n/zh-TW.json
  module/war_archives/assets.py
  module/war_archives/dictionary.py
Labels: game event / 游戏活动
