Repository LmeSzinc/AzurLaneAutoScript, pull requests merged in 2025-05, with the labels that each got.

#4768 Upd:[TW]Event:Ode of Everblooming Crimson
  campaign/Readme.md
  module/config/argument/args.json
  module/config/i18n/zh-TW.json
Labels: Server: TW / 台服, game event / 游戏活动

#4781 Upd: [EN] Add missing scheduler and setting sections
  README_en.md
Labels: documentation / 文档, good first issue / 首次贡献

#4799 fix: no need to check counter in akashi shop
  module/os_shop/selector.py
Labels: bug / 缺陷

#4802 Opt: a better limit when items need to be handled amount
  module/os_shop/shop.py
Labels: optimization / 优化

#4807 Upd: [EN] Fix malformed Pull Requests link
  README_en.md
Labels: documentation / 文档

#4817 Feat(eventstory): start game when it is not running
  module/eventstory/eventstory.py
Labels: feature request / 功能请求

#4827 Upd: [MAA] Update MaaFight.Series values and options to include DISABLE and AUTO (Default AUTO)
  config/template.maa.json
  submodule/AlasMaaBridge/module/config/argument/args.json
  submodule/AlasMaaBridge/module/config/argument/argument.yaml
  submodule/AlasMaaBridge/module/config/config_generated.py
  submodule/AlasMaaBridge/module/config/i18n/en-US.json
  submodule/AlasMaaBridge/module/config/i18n/ja-JP.json
  submodule/AlasMaaBridge/module/config/i18n/zh-CN.json
  submodule/AlasMaaBridge/module/config/i18n/zh-TW.json
Labels: Submodule: MAA / MAA插件

#4849 tmp: [JP] asset SUPPLY_PACK_CHECK
  assets/jp/ui/SUPPLY_PACK_CHECK.png
  module/ui/assets.py
Labels: assets issue / 资源适配问题, Server: JP / 日服
