Repository LmeSzinc/AzurLaneAutoScript, pull requests merged in 2025-08, with the labels that each got.

#4996 Upd: event_20221124_cn rerun entrance
  campaign/Readme.md
  module/config/argument/args.json
  module/config/argument/override.yaml
  module/config/config_updater.py
  module/config/i18n/en-US.json
  module/config/i18n/ja-JP.json
  module/config/i18n/zh-CN.json
Labels: game event / 游戏活动

#5002 Fix: EN-retire assets
  assets/en/retire/DOCK_AMOUNT.png
  assets/en/retire/EMPTY_ENHANCE_SLOT_PLUS.png
  module/retire/assets.py
Labels: assets issue / 资源适配问题, Server: EN / EN服

#5010 Fix: Include GEMS_FARMINGS in event time limit task list
  module/campaign/campaign_event.py
Labels: bug / 缺陷

#5078 Fix: [EN] shop and supply tasks + other hotfixes
  assets/en/freebies/FREE_SUPPLY_PACK.BUTTON.png
  assets/en/freebies/FREE_SUPPLY_PACK.png
  assets/en/shop/SHOP_CLICK_SAFE_AREA.png
  assets/en/shop/SHOP_OCR_OIL.png
  assets/en/shop/SHOP_OCR_OIL_CHECK.png
  assets/en/shop/SHOP_REFRESH.png
  assets/en/ui/MUNITIONS_CHECK.png
  assets/en/ui/SHOP_CHECK.png
  assets/en/ui/SHOP_GOTO_SUPPLY_PACK.BUTTON.png
  assets/en/ui/SHOP_GOTO_SUPPLY_PACK.png
  assets/en/ui/SUPPLY_PACK_CHECK.png
  module/freebies/assets.py
  module/shipyard/shipyard_reward.py
  module/shop/assets.py
  module/shop/shop_core.py
  module/shop/shop_general.py
  module/shop/shop_guild.py
  module/shop/shop_medal.py
  module/shop/shop_merit.py
  module/shop/shop_reward.py
  module/shop/shop_status.py
  module/shop/shop_voucher.py
  module/shop/ui.py
  module/tactical/tactical_class.py
  module/ui/assets.py
Labels: assets issue / 资源适配问题, feature request / 功能请求

#5081 Fix: [EN] shop task; grid now uniform with other servers
  assets/en/shop/SHOP_OCR_OIL.png
  assets/en/shop/SHOP_OCR_OIL_CHECK.png
  assets/en/ui/MUNITIONS_CHECK.png
  assets/en/ui/SUPPLY_PACK_CHECK.png
  module/shop/assets.py
  module/shop/shop_core.py
  module/shop/shop_general.py
  module/shop/shop_guild.py
  module/shop/shop_medal.py
  module/shop/shop_merit.py
  module/shop/ui.py
  module/ui/assets.py
Labels: bug / 缺陷, assets issue / 资源适配问题

#5063 Fix: MetaReward undefined category
  module/os_ash/meta.py
Labels: bug / 缺陷

#5066 Fix: OSDaemon.combat_status() should accept 'no_searching'
  module/os_combat/combat.py
Labels: bug / 缺陷
